confluentinc/confluent-kafka-dotnet

src/Confluent.Kafka/Consumer.cs
src/Confluent.Kafka/Internal/SafeDictionary.cs
src/Confluent.Kafka/Producer.cs

fixes #18. also fixied up some topicConfigHandle related stuff.
@edenhill

fixes possible race condition in getKafkaTopicHandle

---

src/Confluent.Kafka/Serialization/StringDeserializer.cs
test/Confluent.Kafka.UnitTests/Serialization/String.cs

fixes issue #22

---

examples/AdvancedConsumer/Program.cs
src/Confluent.Kafka/Consumer.cs
src/Confluent.Kafka/Structs/Message.cs
test/Confluent.Kafka.Benchmark/BenchmarkConsumer.cs
test/Confluent.Kafka.IntegrationTests/Tests/AssignOverloads.cs
test/Confluent.Kafka.IntegrationTests/Tests/AssignPastEnd.cs
test/Confluent.Kafka.IntegrationTests/Tests/DuplicateConsumerAssign.cs
test/Confluent.Kafka.IntegrationTests/Tests/NullVsEmpty.cs
test/Confluent.Kafka.IntegrationTests/Tests/OnLog.cs

@edenhill @ewencp 
Addresses issue #25

new Consumer.Assign overload

---

src/Confluent.Kafka/Consumer.cs
src/Confluent.Kafka/Producer.cs

resolves issue #33 
@edenhill @ewencp

maintain reference to callback delegates in Producer+Consumer

---

src/Confluent.Kafka/Consumer.cs
test/Confluent.Kafka.IntegrationTests/Tests/OnPartitionsAssignedNotSet.cs

enabling OnPartitionsAssigned fallback on deserializing Consumer

---

examples/AdvancedConsumer/Program.cs
src/Confluent.Kafka/Consumer.cs
test/Confluent.Kafka.UnitTests/Consumer.cs

new Consumer() fail fast when no group.id

---

test/Confluent.Kafka.IntegrationTests/Tests/Metadata.cs

A negative side effect of making the `Metadata` (and child) structs immutable is that `JsonConvert.DeserializeObject` can no longer be used to automatically interpret a JSON serialized `Metadata` object.
I still believe this was a good thing to do though, all things considered.
Note: I'll be renaming this test to something more descriptive in a future PR that re-organizes the tests.
@edenhill

fixed metadata test after Metadata struct et. al. made immutable

---

.travis.yml
test/Confluent.Kafka.VerifiableClient/Program.cs
test/Confluent.Kafka.VerifiableClient/globals.json

These clients now pass the vanilla kafkatests client tests.

Completed kafkatest verifiable clients

---

src/Confluent.Kafka/project.json

this was errantly included in PR #38

netcoreapp1.0 -> netstandard1.3

---

README.md

added intro to README

---

src/Confluent.Kafka/Impl/SafeKafkaHandle.cs
src/Confluent.Kafka/Producer.cs
test/Confluent.Kafka.IntegrationTests/Tests/AssignOverloads.cs
test/Confluent.Kafka.IntegrationTests/Tests/AssignPastEnd.cs
test/Confluent.Kafka.IntegrationTests/Tests/DeserializingConsumer_Consume.cs
test/Confluent.Kafka.IntegrationTests/Tests/DeserializingConsumer_Poll.cs
test/Confluent.Kafka.IntegrationTests/Tests/DuplicateConsumerAssign.cs
test/Confluent.Kafka.IntegrationTests/Tests/GarbageCollect.cs
test/Confluent.Kafka.IntegrationTests/Tests/ListGroup.cs
test/Confluent.Kafka.IntegrationTests/Tests/NullVsEmpty.cs
test/Confluent.Kafka.IntegrationTests/Tests/OnLog.cs
test/Confluent.Kafka.IntegrationTests/Tests/OnPartitionsAssignedNotSet.cs
test/Confluent.Kafka.IntegrationTests/Tests/Producer_ProduceAsync_DeliveryHandler.cs
test/Confluent.Kafka.IntegrationTests/Tests/Producer_ProduceAsync_Null_DeliveryHandler.cs
test/Confluent.Kafka.IntegrationTests/Tests/Producer_ProduceAsync_Null_Task.cs
test/Confluent.Kafka.IntegrationTests/Tests/Producer_ProduceAsync_Task.cs
test/Confluent.Kafka.IntegrationTests/Tests/SerializingProducer_ProduceAsync_DeliveryHandler.cs
test/Confluent.Kafka.IntegrationTests/Tests/SerializingProducer_ProduceAsync_Null_DeliveryHandler.cs
test/Confluent.Kafka.IntegrationTests/Tests/SerializingProducer_ProduceAsync_Null_Task.cs
test/Confluent.Kafka.IntegrationTests/Tests/SerializingProducer_ProduceAsync_Task.cs
test/Confluent.Kafka.IntegrationTests/Tests/SimpleProduceConsume.cs
test/Confluent.Kafka.IntegrationTests/Tests/WatermarkOffsets.cs
test/Confluent.Kafka.IntegrationTests/Util.cs

fixes incorrect timestamps in delivery report + consumed messages

---

README.md

should have been done earlier.

removed developer preview notification from README

---

src/Confluent.Kafka/Consumer.cs
src/Confluent.Kafka/Internal/SafeDictionary.cs
src/Confluent.Kafka/KafkaException.cs
src/Confluent.Kafka/Producer.cs
src/Confluent.Kafka/Serialization/StringSerializer.cs
src/Confluent.Kafka/Timestamp.cs

Fix invalid formated documentation

---

src/Confluent.Kafka/Confluent.Kafka.csproj
src/Confluent.Kafka/Impl/LibRdKafka.cs
src/Confluent.Kafka/Impl/SafeConfigHandle.cs
src/Confluent.Kafka/Impl/SafeKafkaHandle.cs
src/Confluent.Kafka/Impl/SafeTopicConfigHandle.cs
src/Confluent.Kafka/Internal/Util.cs
src/Confluent.Kafka/Producer.cs

Solve #96 
Just had to re implement the Marshal generic functions from https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Runtime/InteropServices/Marshal.cs

Change net451 to net45

---

examples/AdvancedProducer/Program.cs

Hello, I am a developer at Sunrise Brokers and am looking to make heavy use of Kafka using .NET clients. I would like to contribute to this project and this is a simple first-time commit as I am new to contributing on github. If I am doing this wrong please let me know. Thanks.
The change fixes an index out of bounds exception when no arguments are supplied, due to the validation check being in the wrong place.

Fixed args length check

---

src/Confluent.Kafka/Impl/SafeKafkaHandle.cs
src/Confluent.Kafka/Producer.cs
src/Confluent.Kafka/Timestamp.cs
test/Confluent.Kafka.IntegrationTests/Confluent.Kafka.IntegrationTests.csproj
test/Confluent.Kafka.IntegrationTests/Tests/DeserializingConsumer_Consume.cs
test/Confluent.Kafka.IntegrationTests/Tests/DeserializingConsumer_Poll.cs
test/Confluent.Kafka.IntegrationTests/Tests/Producer_ProduceAsync_DeliveryHandler.cs
test/Confluent.Kafka.IntegrationTests/Tests/Producer_ProduceAsync_Null_DeliveryHandler.cs
test/Confluent.Kafka.IntegrationTests/Tests/Producer_ProduceAsync_Null_Task.cs
test/Confluent.Kafka.IntegrationTests/Tests/Producer_ProduceAsync_Task.cs
test/Confluent.Kafka.IntegrationTests/Tests/SerializingProducer_ProduceAsync_DeliveryHandler.cs
test/Confluent.Kafka.IntegrationTests/Tests/SerializingProducer_ProduceAsync_Null_DeliveryHandler.cs
test/Confluent.Kafka.IntegrationTests/Tests/SerializingProducer_ProduceAsync_Null_Task.cs
test/Confluent.Kafka.IntegrationTests/Tests/SerializingProducer_ProduceAsync_Task.cs
test/Confluent.Kafka.IntegrationTests/Tests/SimpleProduceConsume.cs
test/Confluent.Kafka.UnitTests/Confluent.Kafka.UnitTests.csproj
test/Confluent.Kafka.UnitTests/Message.cs
test/Confluent.Kafka.UnitTests/Timestamp.cs

this is #120 by @treziac  with some tidyup commits from me

Timestamp now based on unix time, not DateTime

---

src/Confluent.Kafka/Impl/LibRdKafka.cs

Fix the case where # was present in path (for Uri) (see @cklaw issue in #133 )
Also in the case of @cklaw with the previous PR #146 , it was not possible to load librdkafka manually with the exception thrown.
I still think it's a good thing to throw if we can't load librkdkafka, but also check first if the user has loaded the lib himself (which should not be common, but I had this case and it seems other may have also)
This will also allow people to easily change the version of librdkafka used without having to hack with the content of nupkg (for example to test fix on librdkafka)
It doesn't seem to be feasible in netcoreapp, will have to do more tests on this (calling LoadLibrary on an other librdkafka seems to still use the librdkafka provided in librdkafka.redist)
As I'm not 100% sure …

Fix librdkafka loading

---

examples/AdvancedConsumer/Program.cs

added OnConsumeError handler to AdvancedConsumer example

---

src/Confluent.Kafka/Consumer.cs

Small fix of probably copy-paste mistake in `OnPartitionsAssigned` unsubscribe handler.

Fix OnPartitionsAssigned unsubscribe handler

---

src/Confluent.Kafka/Consumer.cs
src/Confluent.Kafka/ErrorCode.cs
src/Confluent.Kafka/KafkaException.cs
src/Confluent.Kafka/Serialization/Extensions/Message.cs
test/Confluent.Kafka.IntegrationTests/Tests/DeserializingConsumer_Poll_Error.cs

see #175 for discussion
@treziac @edenhill

Expose deserialization errors via OnConsumeError

---

examples/AdvancedProducer/Program.cs

NullReferenceException on advanced producer

---

src/Confluent.Kafka/Consumer.cs
src/Confluent.Kafka/Impl/SafeKafkaHandle.cs
src/Confluent.Kafka/Producer.cs
test/Confluent.Kafka.IntegrationTests/Tests/AddBroker.cs

Close #204 
@mhowlett 
Integation tests result here: https://travis-ci.org/treziac/confluent-kafka-dotnet/jobs/237930661

Add AddBrokers function

---

src/Confluent.Kafka/Consumer.cs
src/Confluent.Kafka/Impl/SafeKafkaHandle.cs
src/Confluent.Kafka/Producer.cs
test/Confluent.Kafka.IntegrationTests/Tests/AddBroker.cs

* Add AddBrokers function
Close #204
* Remove empty line
* Test AddBroker return
* updated AddBrokers API documentation
* tweaking integration test
* review changes

Add AddBrokers function (#209)

---

appveyor.yml

nuget.org requires title to be unique.

set title of strong name package

---

README.md

making this not out-of-date.
@treziac or @edenhill

updated 'Usage' section of README

---

src/Confluent.Kafka/Confluent.Kafka.csproj

Need to use raw for images to work in nuget

Correct icon url

---

test/Confluent.Kafka.VerifiableClient/Program.cs

Some small fixes on verifiable client

Verifiableclient smallfixes

---

src/Confluent.Kafka/Producer.cs

Fix #257, addition to #205; simple producer and integration tests were broken
Need to merge #148 to be sure integration tests are run

Fix typed producer

---

src/Confluent.Kafka/Impl/LibRdKafka.cs
src/Confluent.Kafka/Impl/SafeConfigHandle.cs
src/Confluent.Kafka/Impl/SafeHandleZeroIsInvalid.cs
src/Confluent.Kafka/Impl/SafeKafkaHandle.cs
src/Confluent.Kafka/Impl/SafeTopicConfigHandle.cs
src/Confluent.Kafka/Impl/SafeTopicHandle.cs
test/Confluent.Kafka.IntegrationTests/Tests/ClosedHandle.cs

Fix #258 
I don't use SafeHandle often so feel free to say if something is missing
Will also have to implement dispose pattern properly on Consumer/Producer and some unit tests

Add check on SafeHandle to prevent AccessViolationException

---

README.md

adding build badges to readme. going to just merge this now, but todo: change over appveyor account to confluentinc's.

added travis and appveyor badges

---

README.md

also testing if appveyor integration works for PRs...

appveyor badge on README.md (for confluentinc account)

---

src/Confluent.Kafka/Consumer.cs
src/Confluent.Kafka/Impl/LibRdKafka.cs
src/Confluent.Kafka/Impl/SafeKafkaHandle.cs
src/Confluent.Kafka/TopicPartitionError.cs
src/Confluent.Kafka/TopicPartitionOffsetError.cs
src/Confluent.Kafka/include_docs.xml
test/Confluent.Kafka.IntegrationTests/Tests/Consumer_Pause_Resume.cs
test/Confluent.Kafka.IntegrationTests/bootstrap-topics.sh
test/Confluent.Kafka.UnitTests/TopicPartitionError.cs

the go client just got these, and we can't let it win... straightforward addition so I just did it.
@treziac or @edenhill

Consumer Pause/Resume methods

---

appveyor.yml

work in progress, not yet for review.

CI API docs generation [WIP]

---

README.md
src/Confluent.Kafka/Confluent.Kafka.csproj
test/Confluent.Kafka.StrongName.UnitTests/Confluent.Kafka.StrongName.UnitTests.csproj

release 0.11.1 versioning

---

README.md
examples/AdvancedConsumer/AdvancedConsumer.csproj
examples/AdvancedProducer/AdvancedProducer.csproj
examples/FSharp/FSharp.fsproj
examples/Misc/Misc.csproj
examples/MultiProducer/MultiProducer.csproj
examples/SimpleConsumer/SimpleConsumer.csproj
examples/SimpleProducer/SimpleProducer.csproj
src/Confluent.Kafka/Confluent.Kafka.csproj
test/Confluent.Kafka.Benchmark/Confluent.Kafka.Benchmark.csproj
test/Confluent.Kafka.IntegrationTests/Confluent.Kafka.IntegrationTests.csproj
test/Confluent.Kafka.StrongName.UnitTests/Confluent.Kafka.StrongName.UnitTests.csproj
test/Confluent.Kafka.UnitTests/Confluent.Kafka.UnitTests.csproj
test/Confluent.Kafka.VerifiableClient/Confluent.Kafka.VerifiableClient.csproj

@edenhill - opening this PR so appveyor will produce a CI nuget package I can test. 
should be good to go, but will test it first.

added back implicit reference to librdkafka.redist

---

src/Confluent.Kafka/Consumer.cs
src/Confluent.Kafka/Impl/LibRdKafka.cs
src/Confluent.Kafka/Impl/SafeKafkaHandle.cs
src/Confluent.Kafka/include_docs.xml
test/Confluent.Kafka.IntegrationTests/Tests/Consumer_Seek.cs

Opening this PR now so appveyor creates a nuget package with .Seek on the consumer. Requested in #290.
Currently WIP. I delayed finishing testing of this because a bug in librdkafka (now resolved but unreleased) prevents them from passing.

Adding Consumer.Seek

---

src/Confluent.Kafka/Consumer.cs
test/Confluent.Kafka.IntegrationTests/Tests/Consumer_StoreOffsets.cs

store_offsets fixes

---

README.md

added link to api docs

---

src/Confluent.Kafka/ErrorCode.cs
src/Confluent.Kafka/Library.cs
test/Confluent.Kafka.UnitTests/Error.cs
test/Confluent.Kafka.UnitTests/InvalidHandle.cs
test/Confluent.Kafka.UnitTests/Library.cs
test/Confluent.Kafka.UnitTests/TopicPartitionError.cs
test/Confluent.Kafka.UnitTests/TopicPartitionOffsetError.cs

@edenhill - some small changes that would have prevented issue #390 happening.

Load librdkafka automatically on Library.Version etc.

---

src/Confluent.Kafka/Producer.cs

removing some comments that are no longer relevant after #410.

removed comments related to default.topic.config

---

src/Confluent.Kafka.Avro/Confluent.Kafka.Avro.csproj
src/Confluent.SchemaRegistry/Confluent.SchemaRegistry.csproj

@edenhill - forgot to put metadata in the sr and avro project files (which ends up in the nuget packages & on nuget.org)

Confluent.SchemaRegistry + Confluent.Kafka.Avro project metadata

---

examples/AvroGeneric/AvroGeneric.csproj
examples/AvroGeneric/packages.config
examples/AvroSpecific/AvroSpecific.csproj
src/Confluent.Kafka.Avro/Confluent.Kafka.Avro.csproj
src/Confluent.Kafka/Serialization/Extensions/Message.cs
test/Confluent.Kafka.Avro.IntegrationTests/Confluent.Kafka.Avro.IntegrationTests.csproj
test/Confluent.Kafka.Avro.IntegrationTests/Tests/ProduceConsume.cs
test/Confluent.Kafka.Avro.IntegrationTests/Tests/SharedSchemaRegistryClient.cs
test/Confluent.Kafka.Avro.UnitTests/Confluent.Kafka.Avro.UnitTests.csproj

this is dependent on merging https://github.com/confluentinc/avro/pull/5 . opening now to get a public CI build so people eager for this functionality can start testing it.

Avro serde support for .net standard 2.0

---

README.md

i'll update the actual version numbers in the final commit before release.

updated docs for 0.11.4 functionality

---

README.md

avrogen instructions -> readme

---

README.md
examples/ConfluentCloud/ConfluentCloud.csproj
examples/ConfluentCloud/Program.cs

An example demonstrating use of the client with confluent cloud.

added confluent cloud example

---

README.md

once on nuget, will verify this works before merging.

avrogen is now available as a .net core tool

---

src/Confluent.Kafka/Producer.cs

Fixed a memory leak bug where ProduceAsync was NOT disposing CancellationTokenRegister object when calling Register.

ProduceAsync not disposing CancellationTokenRegister object

---

CHANGELOG.md
README.md
examples/AdminClient/AdminClient.csproj
examples/AvroBlogExamples/AvroBlogExamples.csproj
examples/AvroGeneric/AvroGeneric.csproj
examples/AvroSpecific/AvroSpecific.csproj
examples/ConfluentCloud/ConfluentCloud.csproj
examples/Consumer/Consumer.csproj
examples/MultiProducer/MultiProducer.csproj
examples/Producer/Producer.csproj
src/Confluent.Kafka.Avro/Confluent.Kafka.Avro.csproj
src/Confluent.Kafka/Confluent.Kafka.csproj
src/Confluent.SchemaRegistry/Confluent.SchemaRegistry.csproj
test/Confluent.Kafka.StrongName.UnitTests/Confluent.Kafka.StrongName.UnitTests.csproj

reference librdkafka 1.0.0-PRE1

---

src/Confluent.Kafka/Config.cs

`Config.cs` generated from librdkafka v1.0.0-PRE1.

updated strong config

---

src/Confluent.Kafka/Offset.cs
src/Confluent.Kafka/Partition.cs

resolves #682
TL;DR:
Convert
`public static Offset Beginning { get { return new Offset(RD_KAFKA_OFFSET_BEGINNING); } }`
to
`public static readonly Offset Beginning = new Offset(RD_KAFKA_OFFSET_BEGINNING);`

convert static properties

---

src/Confluent.Kafka/Confluent.Kafka.csproj

Fix when not installed librdkafka.redist cannot load librdkafka.dll in WebApplication project

Fix when not installed librdkafka.redist cannot load librdkafka.dll

---

src/Confluent.SchemaRegistry.Serdes/AvroSerializer.cs
src/Confluent.SchemaRegistry/CachedSchemaRegistryClient.cs
src/Confluent.SchemaRegistry/SchemaRegistryConfig.cs
test/Confluent.SchemaRegistry.IntegrationTests/Tests/BasicAuth.cs

addresses #679. this was accidentally omitted from 1.0-beta2, probably because at one point i was considering not including it.

added SchemaRegistryConfigBasicAuthCredentialsSource

---

src/Confluent.Kafka/Impl/NativeMethods/NativeMethods.cs
src/Confluent.Kafka/Impl/NativeMethods/NativeMethods_Centos7.cs
src/Confluent.Kafka/Impl/NativeMethods/NativeMethods_Debian9.cs

resolves #689, see also #766
integration tests pass

fix rd_kafka_event_type method signature

---

src/Confluent.SchemaRegistry/CachedSchemaRegistryClient.cs
src/Confluent.SchemaRegistry/ISchemaRegistryClient.cs
src/Confluent.SchemaRegistry/Rest/IRestService.cs
src/Confluent.SchemaRegistry/Rest/RestService.cs
test/Confluent.SchemaRegistry.IntegrationTests/Tests/GetSubjectVersions.cs

Resolves #761.
Adds an integration tests for a newly added method which passes.

Adds GET subject versions in the registry client

---

src/Confluent.Kafka/AdminClientBuilder.cs
src/Confluent.Kafka/ConsumerBuilder.cs
src/Confluent.Kafka/DependentProducerBuilder.cs
src/Confluent.Kafka/ProducerBuilder.cs
test/Confluent.Kafka.IntegrationTests/TemporaryTopic.cs
test/Confluent.Kafka.IntegrationTests/Tests/Builder_CustomDefaults.cs
test/Confluent.Kafka.IntegrationTests/Tests/SimpleProduceConsume.cs
test/Confluent.Kafka.IntegrationTests/Tests/Timestamps.cs
test/Confluent.Kafka.VerifiableClient/Program.cs
test/Confluent.SchemaRegistry.Serdes.IntegrationTests/TemporaryTopic.cs

thanks for pointing this out @Fresa!
https://github.com/confluentinc/confluent-kafka-dotnet/issues/708#issuecomment-462850842

builder classes should return interfaces

---

src/Confluent.Kafka/Producer.cs

Resolving issue #794.
Note that this pull request may break some test, as I have never set up a local Kafka cluster and I do not want to delay this pull request. So no integration test has been run prior to this pull request

PersistenceStatus not set correctly

---

.github/ISSUE_TEMPLATE

updated to ask for a complete minimal program demonstrating the problem. this will make life easier many times over.

updated issue template

---

src/ConfigGen/Program.cs
src/Confluent.Kafka/Consumer.cs
src/Confluent.Kafka/Producer.cs
src/Confluent.SchemaRegistry/SchemaRegistryConfig.cs

Remove .ToString() calls on members that are strings

remove unnecessary ToString

---

src/Confluent.Kafka/ConsumerBuilder.cs
src/Confluent.Kafka/ProducerBuilder.cs

Use interfaces in Set*Handler delegates

use IConsumer/IProducer

---

CHANGELOG.md
src/Confluent.Kafka/AdminClient.cs
src/Confluent.Kafka/AdminClientBuilder.cs
src/Confluent.Kafka/Consumer.cs
src/Confluent.Kafka/ConsumerBuilder.cs
src/Confluent.Kafka/DependentAdminClientBuilder.cs
src/Confluent.Kafka/DependentProducerBuilder.cs
src/Confluent.Kafka/Producer.cs
src/Confluent.Kafka/ProducerBuilder.cs
test/Confluent.Kafka.IntegrationTests/Tests/AddBroker.cs
test/Confluent.Kafka.IntegrationTests/Tests/AdminClient_CreatePartitions.cs
test/Confluent.Kafka.IntegrationTests/Tests/AdminClient_CreateTopics.cs
test/Confluent.Kafka.IntegrationTests/Tests/Producer_Handles.cs
test/Confluent.Kafka.IntegrationTests/Tests/WatermarkOffsets.cs

address #886 - an elementary error on my part which i was blind to having looked over the API now so many times.

make client classes internal

---

src/Confluent.Kafka/Consumer.cs
src/Confluent.Kafka/Producer.cs

@edenhill - I want to talk about how error / log handlers work in an upcoming blog post, so really good to get this in now.

don't set callbacks if not configured

---

src/Confluent.Kafka/Consumer.cs
src/Confluent.Kafka/Producer.cs

Fix exception

---

examples/AvroSpecific/Program.cs
src/Confluent.Kafka/LogMessage.cs

changed wording in `AvroSepecific` so that it wouldn't have caused the confusion in #710.
and a tiny whoops.

2 minor things

---

README.md
src/Confluent.Kafka/Confluent.Kafka.csproj
src/Confluent.SchemaRegistry/Confluent.SchemaRegistry.csproj

added netstandard2.0 target

---

README.md

Just a small grammar improvement

README.md: grammar improvement

---

README.md
examples/AdminClient/AdminClient.csproj
examples/AvroBlogExamples/AvroBlogExamples.csproj
examples/AvroGeneric/AvroGeneric.csproj
examples/AvroSpecific/AvroSpecific.csproj
examples/ConfluentCloud/ConfluentCloud.csproj
examples/Consumer/Consumer.csproj
examples/MultiProducer/MultiProducer.csproj
examples/Producer/Producer.csproj
examples/Protobuf/Protobuf.csproj
src/Confluent.Kafka/Confluent.Kafka.csproj
src/Confluent.SchemaRegistry.Serdes/Confluent.SchemaRegistry.Serdes.csproj
src/Confluent.SchemaRegistry/Confluent.SchemaRegistry.csproj

note: changelog not yet update.

-> 1.2.0-RC1

---

examples/ConfluentCloud/Program.cs

these config settings are not needed post v1.0.

simplify ccloud config

---

README.md

Set year to 2019

---

src/Confluent.Kafka/Consumer.cs
src/Confluent.Kafka/Producer.cs

There is no need to use generics on the nested private  classes (the types always align).
Remove the <K, V> parts and just use the <TKey, TValue> from the parent

simplify P&C generics

---

CHANGELOG.md
README.md
examples/AdminClient/AdminClient.csproj
examples/AvroBlogExamples/AvroBlogExamples.csproj
examples/AvroGeneric/AvroGeneric.csproj
examples/AvroSpecific/AvroSpecific.csproj
examples/ConfluentCloud/ConfluentCloud.csproj
examples/Consumer/Consumer.csproj
examples/MultiProducer/MultiProducer.csproj
examples/Producer/Producer.csproj
examples/Protobuf/Protobuf.csproj
examples/Transactions/Transactions.csproj
src/Confluent.Kafka/Config_gen.cs
src/Confluent.Kafka/Confluent.Kafka.csproj
src/Confluent.SchemaRegistry.Serdes/Confluent.SchemaRegistry.Serdes.csproj
src/Confluent.SchemaRegistry/Confluent.SchemaRegistry.csproj

-> v1.4.0-RC1/c

---

src/Confluent.Kafka/Consumer.cs
src/Confluent.Kafka/Impl/SafeKafkaHandle.cs
src/Confluent.Kafka/Producer.cs
src/Confluent.Kafka/SerializationContext.cs
test/Confluent.Kafka.IntegrationTests/Tests/Headers_SerializationContext.cs
test/Confluent.Kafka.IntegrationTests/Tests/Transactions_Commit.cs

Make headers available in SerializationContext

---

src/Confluent.SchemaRegistry/Rest/RestService.cs

remove charset=uft8 from content-type header

---

test/Confluent.Kafka.IntegrationTests/Tests/Consumer_Assign.cs

Added test for Consumer.Assign with Offset.Beginning/Offset.End

---

src/Confluent.SchemaRegistry/Rest/RestService.cs

this will hopefully resolve #1258 
regardless, we should be doing this.

UrlEncode subject name

---

src/Confluent.Kafka/Producer.cs

fix for #1287 
@msoler8785 - can you please verify? i'm opening a PR so that appveyor will automatically build the packages (not for merge yet). for instructions on how to reference, see here: https://github.com/confluentinc/confluent-kafka-dotnet#branch-builds
in my quick testing, interestingly i did not actually see unbounded memory growth without this, however there is definitely a problem here.

Dispose ProduceAsync's CancellationTokenRegistration

---

src/Confluent.Kafka/Impl/LibRdKafka.cs
test/Confluent.Kafka.IntegrationTests/Tests/Transactions_Error.cs

Fix infinite recursion bug in error_destroy

---

examples/JsonSerialization/JsonSerialization.csproj
examples/Protobuf/Protobuf.csproj
src/Confluent.Kafka/Impl/LibRdKafka.cs
src/Confluent.Kafka/Impl/MonoSupport.cs
src/Confluent.Kafka/Impl/NativeMethods/NativeMethods_Alpine.cs
src/Confluent.Kafka/Impl/NativeMethods/NativeMethods_Centos7.cs
src/Confluent.Kafka/Impl/NativeMethods/NativeMethods_Debian9.cs

These changes are based closely on the work by @4garbage in #788 
I'm structuring the PR as a series of incremental commits in order to make the changes easy to follow and check.

Mono support

---

examples/Web/RequestTimeConsumer.cs

We can use `BackgroundService` which implements `IHostedService` in order to avoid using our own cancellation token. The token passed to the `ExecuteAsync` method is fired when application is shutting down. We should catch `OperationCanceledException` which may get thrown in Consume if the token is fired. And we loop unless the operation is canceled.

Refactor RequestTimeConsumer.

---

test/Confluent.Kafka.Benchmark/BenchmarkConsumer.cs
test/Confluent.Kafka.Benchmark/BenchmarkProducer.cs
test/Confluent.Kafka.Benchmark/Confluent.Kafka.Benchmark.csproj
test/Confluent.Kafka.Benchmark/Latency.cs
test/Confluent.Kafka.Benchmark/Program.cs

Try not to be too picky on this - more important things to be focused on. Just trying to add some value quickly for something I needed on Friday.

Latency benchmark test

---

test/Confluent.Kafka.IntegrationTests/Tests/Consumer_Drain.cs

integration test for behavior reported as not working

"Drain" integration test

---

src/Confluent.Kafka/Impl/SafeKafkaHandle.cs

ArgumentNullException for Subscribe

---

src/Confluent.SchemaRegistry.Serdes.Avro/AvroDeserializer.cs
src/Confluent.SchemaRegistry.Serdes.Avro/AvroSerializer.cs

ConfigureAwait(false) in Avro serdes

---

CHANGELOG.md
src/Confluent.Kafka/Confluent.Kafka.csproj
src/Confluent.Kafka/Impl/LibRdKafka.cs
src/Confluent.Kafka/Impl/NativeMethods/NativeMethods_Centos6.cs

i will push a the CI build of this to nuget to facilitate testing.

librdkafka.redist 1.6.0-PRE6

---

src/Confluent.Kafka/Producer.cs

need to prevent partitioner delegate addresses moving during GC compaction, otherwise 💥

Pin custom partitioners

---

src/Confluent.SchemaRegistry.Serdes.Protobuf/ProtobufSerializer.cs

This PR fixes issue #1523
List of result were updating from different tasks.

Fix race condition in RegisterOrGetReferences method

---

CHANGELOG.md
src/Confluent.SchemaRegistry.Serdes.Avro/Confluent.SchemaRegistry.Serdes.Avro.csproj
test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Confluent.SchemaRegistry.Serdes.IntegrationTests.csproj
test/Confluent.SchemaRegistry.Serdes.UnitTests/Confluent.SchemaRegistry.Serdes.UnitTests.csproj

Bump Apache.Avro from 1.10.1 to 1.10.2

---

src/Confluent.SchemaRegistry.Serdes.Json/JsonSerializer.cs

to properly list failed property names
Fixes https://github.com/confluentinc/confluent-kafka-dotnet/issues/1597

Fixed exception message expression

---

src/Confluent.SchemaRegistry.Serdes.Avro/AvroSerializer.cs
src/Confluent.SchemaRegistry.Serdes.Avro/AvroSerializerConfig.cs
src/Confluent.SchemaRegistry.Serdes.Avro/GenericSerializerImpl.cs
src/Confluent.SchemaRegistry.Serdes.Avro/SpecificSerializerImpl.cs
src/Confluent.SchemaRegistry.Serdes.Json/JsonSerializer.cs
src/Confluent.SchemaRegistry.Serdes.Json/JsonSerializerConfig.cs
src/Confluent.SchemaRegistry.Serdes.Protobuf/ProtobufDeserializer.cs
src/Confluent.SchemaRegistry.Serdes.Protobuf/ProtobufDeserializerConfig.cs
src/Confluent.SchemaRegistry.Serdes.Protobuf/ProtobufSerializer.cs
src/Confluent.SchemaRegistry.Serdes.Protobuf/ProtobufSerializerConfig.cs
src/Confluent.SchemaRegistry.Serdes.Protobuf/Utils.cs
test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests_Avro/AutoRegisterSchemaDisabled.cs

Also 
- add skip.known.types config for Protobuf serializer
- fix serialization of message indexes per https://docs.confluent.io/platform/current/schema-registry/serdes-develop/index.html#wire-format

Enhance serializers with use.latest.version config

---

README.md
examples/AvroSpecific/README.md

Making Avro harder to discover because the Apache.Avro implementation quality is a support nightmare for us.

Deemphasize Avro

---

test/Confluent.Kafka.IntegrationTests/Tests/Consumer_MissingCommits.cs

Relates to an RCCA I was investigating. The test passes.

Added missing commits integration test

---

src/Confluent.Kafka/Confluent.Kafka.csproj
src/Confluent.Kafka/Impl/LibRdKafka.cs
src/Confluent.Kafka/Impl/PlatformApis.cs

[FIX] Confluence kafka-dotnet causes app to crash on alpine when MUSL is installed #1714

---

src/Confluent.Kafka/Confluent.Kafka.csproj
src/Confluent.Kafka/Impl/LibRdKafka.cs
src/Confluent.Kafka/Impl/MonoSupport.cs
src/Confluent.Kafka/Impl/NativeMethods/NativeMethods_Alpine.cs
src/Confluent.Kafka/Impl/NativeMethods/NativeMethods_Centos6.cs
src/Confluent.Kafka/Impl/NativeMethods/NativeMethods_Centos7.cs
src/Confluent.Kafka/Internal/Util.cs
src/Confluent.Kafka/Producer.cs
test/Confluent.Kafka.UnitTests/Confluent.Kafka.UnitTests.csproj

Removed NET45/46 in favor of NET462 and cleaned up code no longer required

Remove NET45/NET46 in favor of NET462 #1779

---

CHANGELOG.md
README.md
src/Confluent.SchemaRegistry.Serdes.Protobuf/Confluent.SchemaRegistry.Serdes.Protobuf.csproj
test/Confluent.SchemaRegistry.IntegrationTests/Confluent.SchemaRegistry.IntegrationTests.csproj
test/Confluent.SchemaRegistry.Serdes.UnitTests/Confluent.SchemaRegistry.Serdes.UnitTests.csproj

Protobuf -> 3.15.0 (CVE-2021-22570) + remove travis button

---

src/Confluent.SchemaRegistry/Confluent.SchemaRegistry.csproj
test/Confluent.Kafka.IntegrationTests/Confluent.Kafka.IntegrationTests.csproj
test/Confluent.Kafka.VerifiableClient/Confluent.Kafka.VerifiableClient.csproj

dependabot alerts is warning us about this.

Address security vulnerability in Newtonsoft.Json

---

src/Confluent.Kafka/ErrorCode.cs

c.f. https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L576

Added missing broker error codes

---

CHANGELOG.md
README.md
examples/AdminClient/AdminClient.csproj
examples/AvroBlogExamples/AvroBlogExamples.csproj
examples/AvroGeneric/AvroGeneric.csproj
examples/AvroSpecific/AvroSpecific.csproj
examples/ConfluentCloud/ConfluentCloud.csproj
examples/Consumer/Consumer.csproj
examples/ExactlyOnce/ExactlyOnce.csproj
examples/ExactlyOnceOldBroker/ExactlyOnceOldBroker.csproj
examples/JsonSerialization/JsonSerialization.csproj
examples/MultiProducer/MultiProducer.csproj
examples/Producer/Producer.csproj
examples/Protobuf/Protobuf.csproj
examples/Web/Web.csproj
src/Confluent.Kafka/Confluent.Kafka.csproj
src/Confluent.SchemaRegistry.Serdes.Avro/Confluent.SchemaRegistry.Serdes.Avro.csproj
src/Confluent.SchemaRegistry.Serdes.Json/Confluent.SchemaRegistry.Serdes.Json.csproj
src/Confluent.SchemaRegistry.Serdes.Protobuf/Confluent.SchemaRegistry.Serdes.Protobuf.csproj
src/Confluent.SchemaRegistry/Confluent.SchemaRegistry.csproj

Note: References librdkafka 1.9.2. Not ideal, but we've had the argument about 4 part version codes before.

-> nuget version 1.9.3

---

examples/ExactlyOnce/Program.cs
examples/ExactlyOnce/appsettings.json

Partial re-work of new eos example

Partial re-work of new eos example

---

.travis.yml
Makefile

Update Travis .NET version

---

README.md
examples/AdminClient/AdminClient.csproj
examples/AvroBlogExamples/AvroBlogExamples.csproj
examples/AvroGeneric/AvroGeneric.csproj
examples/AvroSpecific/AvroSpecific.csproj
examples/ConfluentCloud/ConfluentCloud.csproj
examples/Consumer/Consumer.csproj
examples/ExactlyOnce/ExactlyOnce.csproj
examples/ExactlyOnceOldBroker/ExactlyOnceOldBroker.csproj
examples/JsonSerialization/JsonSerialization.csproj
examples/Producer/Producer.csproj
examples/Protobuf/Protobuf.csproj
src/Confluent.Kafka/Config_gen.cs
src/Confluent.Kafka/Confluent.Kafka.csproj
src/Confluent.SchemaRegistry.Serdes.Avro/Confluent.SchemaRegistry.Serdes.Avro.csproj
src/Confluent.SchemaRegistry.Serdes.Json/Confluent.SchemaRegistry.Serdes.Json.csproj
src/Confluent.SchemaRegistry.Serdes.Protobuf/Confluent.SchemaRegistry.Serdes.Protobuf.csproj
src/Confluent.SchemaRegistry/Confluent.SchemaRegistry.csproj

Changes done:
1. Update version reference to 2.0.2 everywhere.
2. Update the config to latest config.
https://confluentinc.atlassian.net/wiki/spaces/CLIENTS/pages/2914584782/Things+To+Know+About+The+.NET+Client

Nuget version 2.0.2

---

CHANGELOG.md
README.md
examples/AdminClient/AdminClient.csproj
examples/AvroBlogExamples/AvroBlogExamples.csproj
examples/AvroGeneric/AvroGeneric.csproj
examples/AvroSpecific/AvroSpecific.csproj
examples/Configuration/Configuration.csproj
examples/ConfluentCloud/ConfluentCloud.csproj
examples/Consumer/Consumer.csproj
examples/ExactlyOnce/ExactlyOnce.csproj
examples/ExactlyOnceOldBroker/ExactlyOnceOldBroker.csproj
examples/JsonSerialization/JsonSerialization.csproj
examples/OAuthConsumer/OAuthConsumer.csproj
examples/OAuthOIDC/OAuthOIDC.csproj
examples/OAuthProducer/OAuthProducer.csproj
examples/Producer/Producer.csproj
examples/Protobuf/Protobuf.csproj
examples/TlsAuth/TlsAuth.csproj
src/Confluent.Kafka/Config_gen.cs
src/Confluent.Kafka/Confluent.Kafka.csproj
src/Confluent.SchemaRegistry.Serdes.Avro/Confluent.SchemaRegistry.Serdes.Avro.csproj
src/Confluent.SchemaRegistry.Serdes.Json/Confluent.SchemaRegistry.Serdes.Json.csproj
src/Confluent.SchemaRegistry.Serdes.Protobuf/Confluent.SchemaRegistry.Serdes.Protobuf.csproj
src/Confluent.SchemaRegistry/Confluent.SchemaRegistry.csproj

and confluent-kafka-dotnet v2.1.0

librdkafka v2.1.0-RC3

---

CHANGELOG.md
src/Confluent.Kafka/ConsumeResult.cs
src/Confluent.Kafka/Consumer.cs
src/Confluent.Kafka/IConsumer.cs
src/Confluent.Kafka/Impl/LibRdKafka.cs
src/Confluent.Kafka/Impl/NativeMethods/NativeMethods.cs
src/Confluent.Kafka/Impl/NativeMethods/NativeMethods_Alpine.cs
src/Confluent.Kafka/Impl/NativeMethods/NativeMethods_Centos6.cs
src/Confluent.Kafka/Impl/NativeMethods/NativeMethods_Centos7.cs
src/Confluent.Kafka/Impl/SafeKafkaHandle.cs
src/Confluent.Kafka/TopicPartitionOffset.cs
src/Confluent.Kafka/TopicPartitionOffsetError.cs
test/Confluent.Kafka.IntegrationTests/Tests/Consumer_Seek.cs

and handle log truncation. .NET changes

KIP-320: Allow fetchers to detect

---

CHANGELOG.md
src/Confluent.SchemaRegistry/CachedSchemaRegistryClient.cs
src/Confluent.SchemaRegistry/ISchemaRegistryClient.cs
src/Confluent.SchemaRegistry/Rest/DataContracts/Compatibility.cs
src/Confluent.SchemaRegistry/Rest/IRestService.cs
src/Confluent.SchemaRegistry/Rest/RestService.cs
test/Confluent.SchemaRegistry.IntegrationTests/Tests/UpdateCompatibility.cs

Hi!
I've added the missing compatibility types and methods to work with them.

Methods for working with compatibility

---

README.md

chore: update readme to fix format :coffee:

chore: update readme to fix format

---

src/Confluent.SchemaRegistry.Rules/BuiltinDeclarations.cs
src/Confluent.SchemaRegistry.Rules/BuiltinLibrary.cs
src/Confluent.SchemaRegistry.Rules/BuiltinOverload.cs
src/Confluent.SchemaRegistry.Rules/CelExecutor.cs
src/Confluent.SchemaRegistry.Rules/Confluent.SchemaRegistry.Rules.csproj
test/Confluent.SchemaRegistry.Serdes.UnitTests/BuiltinFunctions.cs
test/Confluent.SchemaRegistry.Serdes.UnitTests/SerializeDeserialize.cs

Add string helper functions to CEL executor

Add string helper functions to CEL executor

---

examples/AvroGenericEncryption/Program.cs
examples/AvroSpecificEncryption/Program.cs
examples/JsonEncryption/Program.cs
examples/ProtobufEncryption/Program.cs
src/Confluent.SchemaRegistry.Encryption/KmsRegistry.cs
src/Confluent.SchemaRegistry/Rest/DataContracts/Schema.cs

* Improve missing KMS error message
Also enhance examples, some minor cleanup
* Fix tests

Improve missing KMS error message (#6)

---

src/Confluent.SchemaRegistry.Serdes.Json/JsonSchemaResolver.cs
src/Confluent.SchemaRegistry/AsyncSerde.cs
src/Confluent.SchemaRegistry/CachedSchemaRegistryClient.cs
src/Confluent.SchemaRegistry/ISchemaRegistryClient.cs
src/Confluent.SchemaRegistry/Rest/IRestService.cs
src/Confluent.SchemaRegistry/Rest/RestService.cs
test/Confluent.SchemaRegistry.Serdes.UnitTests/BaseSerializeDeserialize.cs

* Include deleted schemas when getting schemas by subect/version
* Minor fix

Include deleted schemas when getting schemas by subject/version (#16)

---

src/Confluent.SchemaRegistry.Encryption.HcVault/HcVaultKmsClient.cs
src/Confluent.SchemaRegistry.Encryption/LocalKmsClient.cs
test/Confluent.SchemaRegistry.Serdes.UnitTests/SerializeDeserialize.cs

* Add CSFLE tests with pre-canned data
* Minor cleanup
* Minor cleanup
* Minor fix
* Minor fix
* Minor fix

Add CSFLE tests with pre-canned data (#22)

---

src/Confluent.SchemaRegistry/AsyncSerde.cs
test/Confluent.SchemaRegistry.Serdes.UnitTests/ProtoSerializeDeserialize.cs

Allow null SchemaRegistryClient in AsyncSerde constructor (#2267)

---

src/Confluent.SchemaRegistry.Serdes.Avro/AvroDeserializer.cs
src/Confluent.SchemaRegistry.Serdes.Avro/AvroSerializer.cs
src/Confluent.SchemaRegistry.Serdes.Avro/GenericDeserializerImpl.cs
src/Confluent.SchemaRegistry.Serdes.Avro/GenericSerializerImpl.cs
src/Confluent.SchemaRegistry.Serdes.Avro/SpecificDeserializerImpl.cs
src/Confluent.SchemaRegistry.Serdes.Avro/SpecificSerializerImpl.cs
src/Confluent.SchemaRegistry.Serdes.Json/JsonDeserializer.cs
src/Confluent.SchemaRegistry.Serdes.Json/JsonSerializer.cs
src/Confluent.SchemaRegistry.Serdes.Protobuf/ProtobufDeserializer.cs
src/Confluent.SchemaRegistry.Serdes.Protobuf/ProtobufSerializer.cs
src/Confluent.SchemaRegistry/AsyncDeserializer.cs
src/Confluent.SchemaRegistry/AsyncSerde.cs
src/Confluent.SchemaRegistry/AsyncSerializer.cs
src/Confluent.SchemaRegistry/RuleRegistry.cs
test/Confluent.SchemaRegistry.Serdes.UnitTests/JsonSerializeDeserialize.cs
test/Confluent.SchemaRegistry.Serdes.UnitTests/ProtoSerializeDeserialize.cs
test/Confluent.SchemaRegistry.Serdes.UnitTests/SerializeDeserialize.cs

* Minor refactor to use RuleRegistry
* Minor cleanup

Minor refactor to use RuleRegistry (#33)

---

CHANGELOG.md
examples/AdminClient/Program.cs
src/Confluent.Kafka/Admin/ConsumerGroupListing.cs
src/Confluent.Kafka/Admin/ListConsumerGroupsOptions.cs
src/Confluent.Kafka/AdminClient.cs
src/Confluent.Kafka/ConsumerGroupType.cs
src/Confluent.Kafka/Impl/LibRdKafka.cs
src/Confluent.Kafka/Impl/NativeMethods/NativeMethods.cs
src/Confluent.Kafka/Impl/NativeMethods/NativeMethods_Alpine.cs
src/Confluent.Kafka/Impl/NativeMethods/NativeMethods_Centos8.cs
src/Confluent.Kafka/Impl/SafeKafkaHandle.cs
test/Confluent.Kafka.IntegrationTests/Tests/AdminClient_ListConsumerGroups.cs

an optional filter to return only groups of given types
Will rebase this PR after it's using `librdkafka.redist v2.6.0-RC2`

[KIP-848 EA] Admin API for listing consumer groups now has

---

src/Confluent.SchemaRegistry.Serdes.Avro/GenericDeserializerImpl.cs
src/Confluent.SchemaRegistry.Serdes.Avro/SpecificDeserializerImpl.cs
src/Confluent.SchemaRegistry.Serdes.Json/JsonDeserializer.cs
test/Confluent.SchemaRegistry.Serdes.UnitTests/SerializeDeserialize.cs

Ensure proper reader schema in rules for deserializer.  Also adds a test

Ensure proper reader schema in rules for deserializer

---

src/Confluent.SchemaRegistry.Serdes.Avro/GenericSerializerImpl.cs
src/Confluent.SchemaRegistry.Serdes.Avro/SpecificSerializerImpl.cs
src/Confluent.SchemaRegistry.Serdes.Json/JsonSerializer.cs
src/Confluent.SchemaRegistry.Serdes.Protobuf/ProtobufSerializer.cs

Minor refactoring to ensure latest schema can change.  Most of the changes are just changes in indenting

Minor refactoring to ensure latest schema can change

---

src/Confluent.SchemaRegistry/CachedSchemaRegistryClient.cs
src/Confluent.SchemaRegistry/Rest/RestService.cs

Rebase [Fixing the validation of the SSL CA Certificate](https://github.com/confluentinc/confluent-kafka-dotnet/pull/2143) to master

Fixing the validation of the SSL CA Certificate

---

src/Confluent.SchemaRegistry/Rest/RestService.cs

Rebase of https://github.com/confluentinc/confluent-kafka-dotnet/pull/2174 to master

(fix #1897) : skip server SSL certs verification when configured

---

src/Confluent.SchemaRegistry/CachedSchemaRegistryClient.cs
src/Confluent.SchemaRegistry/Rest/RestService.cs

Allow proxy to be specified (#2127)

---

CHANGELOG.md
README.md
src/Confluent.Kafka/Confluent.Kafka.csproj

DLL is being loaded, producer and consumer working, with .NET Framework 4.6.2, 4.8 and 4.8.1

Continue supporting .NET Framework.

---

src/Confluent.SchemaRegistry.Serdes.Avro/GenericDeserializerImpl.cs
src/Confluent.SchemaRegistry.Serdes.Avro/SpecificDeserializerImpl.cs
src/Confluent.SchemaRegistry.Serdes.Json/JsonDeserializer.cs
src/Confluent.SchemaRegistry.Serdes.Protobuf/ProtobufDeserializer.cs
src/Confluent.SchemaRegistry/AsyncSerde.cs
test/Confluent.SchemaRegistry.Serdes.UnitTests/BaseSerializeDeserialize.cs

Fixes https://github.com/confluentinc/confluent-kafka-dotnet/issues/2356

Retrieve version for writer schema when getting migrations

---

src/Confluent.SchemaRegistry.Encryption.Aws/AwsKmsClient.cs
src/Confluent.SchemaRegistry.Encryption.Azure/AzureKmsClient.cs
src/Confluent.SchemaRegistry.Encryption.Gcp/GcpKmsClient.cs
src/Confluent.SchemaRegistry.Encryption.HcVault/HcVaultKmsClient.cs

Ensure different key ids use different client instances.

Ensure different key ids use different client instances

---

src/Confluent.SchemaRegistry/AsyncSerde.cs
src/Confluent.SchemaRegistry/RuleOverride.cs
src/Confluent.SchemaRegistry/RuleRegistry.cs
test/Confluent.SchemaRegistry.Serdes.UnitTests/SerializeDeserialize.cs

What
----
Checklist
References
----------
JIRA: 
Test & Review
------------

Add ability to override disable flag and actions on a rule

---

src/Confluent.SchemaRegistry.Encryption.Aws/AwsKmsDriver.cs
src/Confluent.SchemaRegistry.Encryption.Aws/Confluent.SchemaRegistry.Encryption.Aws.csproj

What
----
Minor enhancement to allow AWS roles to be specified. This was tested manually with actual AWS IAM roles.
Checklist
References
----------
JIRA: 
Test & Review
------------

Add AWS AssumeRole support to AWS KMS

---

src/Confluent.SchemaRegistry/Rest/RestService.cs

What
----
Change max retry default from 2 to 3 based on internal review.
Checklist
References
----------
JIRA: 
Test & Review
------------

Minor change to default for client retries

---

src/Confluent.SchemaRegistry/Rest/RestService.cs
test/Confluent.SchemaRegistry.Serdes.UnitTests/SerializeDeserialize.cs

What
----
Checklist
- No
- Yes
References
----------
JIRA: 
Test & Review
------------

MINOR fix to RestService and test

---

CHANGELOG.md

What
----
Checklist
References
----------
JIRA: 
Test & Review
------------

Update changelog for SR for 2.8.0

---

src/Confluent.SchemaRegistry.Encryption/FieldEncryptionExecutor.cs
test/Confluent.SchemaRegistry.Serdes.UnitTests/Configuration.cs

What
----
Enhance error handling for CSFLE configure method
Checklist
References
----------
JIRA: 
Test & Review
------------

DGS-19519 Enhance error handling for CSFLE configure method

---

.gitignore
.semaphore/semaphore.yml
Makefile
service.yml
sonar-project.properties

What
----
Onboard to SonarQube to generate code coverage reports.
Checklist
- **No code changes**
References
----------
JIRA: [DGS-16859](https://confluentinc.atlassian.net/browse/DGS-16859)
Test & Review
------------
[DGS-16859]: https://confluentinc.atlassian.net/browse/DGS-16859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DGS-16859: Onboard repo to SonarQube

---

src/Confluent.SchemaRegistry.Encryption/Rest/DataContracts/RegisteredDek.cs

What
----
Checklist
References
----------
JIRA: 
Test & Review
------------

DGS-19840 Ensure use of DEK object is thread-safe

---

src/Confluent.SchemaRegistry.Serdes.Json/JsonDeserializer.cs
src/Confluent.SchemaRegistry.Serdes.Json/JsonDeserializerConfig.cs
src/Confluent.SchemaRegistry.Serdes.Json/JsonSerializer.cs
src/Confluent.SchemaRegistry.Serdes.Json/JsonSerializerConfig.cs

What
----
fix whitespace formatting
Checklist
References
----------
JIRA: 
Test & Review
------------

MINOR fix whitespace formatting

---

src/Confluent.SchemaRegistry.Encryption/FieldEncryptionExecutor.cs

What
----
Checklist
References
----------
JIRA: 
Test & Review
------------

MINOR refactor of DEK creation

---

src/Confluent.SchemaRegistry.Serdes.Protobuf/DecimalExtensions.cs
src/Confluent.SchemaRegistry.Serdes.Protobuf/DecimalUtils.cs
src/Confluent.SchemaRegistry.Serdes.Protobuf/proto/confluent/type/decimal.proto
test/Confluent.SchemaRegistry.Serdes.UnitTests/ProtoDecimal.cs

What
----
Add utilities to convert decimals from/to Protobuf
Checklist
References
----------
JIRA: 
Test & Review
------------

DGS-20014 Add utilities to convert decimals from/to Protobuf

---

src/Confluent.SchemaRegistry.Serdes.Avro/AvroSerializer.cs
src/Confluent.SchemaRegistry.Serdes.Avro/AvroSerializerConfig.cs
src/Confluent.SchemaRegistry.Serdes.Avro/GenericSerializerImpl.cs
src/Confluent.SchemaRegistry.Serdes.Avro/SpecificSerializerImpl.cs
src/Confluent.SchemaRegistry.Serdes.Json/JsonSerializer.cs
src/Confluent.SchemaRegistry.Serdes.Json/JsonSerializerConfig.cs
src/Confluent.SchemaRegistry.Serdes.Protobuf/ProtobufSerializer.cs
src/Confluent.SchemaRegistry.Serdes.Protobuf/ProtobufSerializerConfig.cs
src/Confluent.SchemaRegistry/AsyncSerde.cs
test/Confluent.SchemaRegistry.Serdes.UnitTests/SerializeDeserialize.cs

What
----
Add support for passing schema ID during serialization
Checklist
References
----------
JIRA: 
Test & Review
------------

Add support for passing schema ID during serialization

---

src/Confluent.SchemaRegistry.Serdes.Protobuf/Confluent.SchemaRegistry.Serdes.Protobuf.csproj
test/Confluent.SchemaRegistry.Serdes.UnitTests/Confluent.SchemaRegistry.Serdes.UnitTests.csproj

What
----
Fix Error CS0433 for apps using this library by excluding protobuf-net.Reflection from being a compile-time transitive dependency.
Fixes https://github.com/confluentinc/confluent-kafka-dotnet/issues/2272
Fixes https://github.com/confluentinc/confluent-kafka-dotnet/issues/2409
Checklist
References
----------
JIRA: 
Test & Review
------------

Fix Error CS0433 for apps using this library

---

src/Confluent.SchemaRegistry/CachedSchemaRegistryClient.cs

We have a large Protobuf schema in our system (over 300 proto dependencies), and the initial schema registration takes nearly **30 seconds**, which is far too long.  
We've identified that we can easily save around **10 seconds** by caching the results of `LookupSchemaAsync` calls.
This PR introduces that caching mechanism.  
Additionally, I’ve added a utility method for `ConcurrentDictionary` that enables safe caching of asynchronous results without requiring a global mutex.  
In future PRs, I plan to build on this utility to eliminate mutexes from other cache calls as well. This should further improve performance in concurrent scenarios involving the schema registry - such as in the `RegisterOrGetReferences` method of `ProtobufSerializer`.
---
- No changes in public API
- Just a perf …

Optimize schema registry client by caching results of LookupSchemaAsync

---

src/Confluent.SchemaRegistry/Utils.cs

What
----
Checklist
References
----------
JIRA: 
Test & Review
------------

Minor change to fix build

---

CHANGELOG.md

What
----
Checklist
References
----------
JIRA: 
Test & Review
------------

Update CHANGELOG for 2.9

---

examples/SchemaRegistryOAuth/Program.cs
examples/SchemaRegistryOAuth/SchemaRegistryOAuth.csproj

What
----
Checklist
References
----------
JIRA: 
Test & Review
------------

Sro auth examples

---

src/Confluent.SchemaRegistry/CachedSchemaRegistryClient.cs

What
----
This change simplifies the caching logic and removes unnecessary format checks on lookup. It should be safe, as we already assume the schema registry returns schemas in the correct format. More importantly, it’s a step toward eliminating the global mutex: to safely drop synchronization, cache misses must depend only on the key. Any logic that depends on schema content or format at lookup time would reintroduce the need for locking—handling it at insertion avoids that.
Checklist
- No changes in public API
- Just a perf optimization, no functional changes.
@rayokota Could you please take a look?

Refactor schema caching to use a composite key for SchemaId and format

---

src/Confluent.SchemaRegistry/Rest/RestService.cs

What
----
Ensure HTTP response object is disposed 
Checklist
References
----------
JIRA: 
Test & Review
------------

Ensure HTTP response object is disposed

---

src/ConfigGen/Program.cs
src/Confluent.Kafka/Config_gen.cs

avoiding warnings because of XML reserved characters. Solves the lack of those fields in docfx generated documentation
What
----
Checklist
References
----------
JIRA: 
Test & Review
------------

Enclose property descriptions with CDATA

---

test/Confluent.Kafka.IntegrationTests/Tests/AdminClient_ListDescribeConsumerGroups.cs

for the classic protocol. To be fixed
What
----
Checklist
References
----------
JIRA: 
Test & Review
------------

Skip hanging test that was disabled until recently

---

src/Confluent.SchemaRegistry.Encryption/FieldEncryptionExecutor.cs

What
----
Checklist
References
----------
JIRA: 
Test & Review
------------

Fix possible NPE in CSFLE executor

---

src/Confluent.SchemaRegistry.Rules/CelExecutor.cs
src/Confluent.SchemaRegistry.Rules/CelFieldExecutor.cs
src/Confluent.SchemaRegistry.Serdes.Avro/GenericDeserializerImpl.cs
src/Confluent.SchemaRegistry.Serdes.Avro/GenericSerializerImpl.cs
src/Confluent.SchemaRegistry.Serdes.Avro/SpecificDeserializerImpl.cs
src/Confluent.SchemaRegistry.Serdes.Avro/SpecificSerializerImpl.cs
src/Confluent.SchemaRegistry.Serdes.Json/JsonDeserializer.cs
src/Confluent.SchemaRegistry.Serdes.Json/JsonSchemaResolver.cs
src/Confluent.SchemaRegistry.Serdes.Json/JsonSerializer.cs
src/Confluent.SchemaRegistry.Serdes.Protobuf/ProtobufDeserializer.cs
src/Confluent.SchemaRegistry/AsyncSerde.cs
src/Confluent.SchemaRegistry/CachedSchemaRegistryClient.cs
src/Confluent.SchemaRegistry/Rest/Authentication/BearerAuthenticationHeaderValueProvider.cs
src/Confluent.SchemaRegistry/Rest/RestService.cs
src/Shared/ConcurrentDictionaryExtensions.cs

What
----
Checklist
References
----------
JIRA: 
Test & Review
------------

Add missing ConfigureAwait calls

---

src/Confluent.SchemaRegistry.Serdes.Protobuf/ProtobufDeserializer.cs
src/Confluent.SchemaRegistry.Serdes.Protobuf/ProtobufSerializer.cs

What
----
Checklist
References
----------
JIRA: 
Test & Review
------------

Raise an error if Protobuf deprecated format is specified

---

CHANGELOG.md
examples/AdminClient/AdminClient.csproj
examples/Configuration/Configuration.csproj
examples/ConfluentCloud/ConfluentCloud.csproj
examples/Consumer/Consumer.csproj
examples/ExactlyOnce/ExactlyOnce.csproj
examples/ExactlyOnceOldBroker/ExactlyOnceOldBroker.csproj
examples/MultiProducer/MultiProducer.csproj
examples/OAuthConsumer/OAuthConsumer.csproj
examples/OAuthOIDC/OAuthOIDC.csproj
examples/OAuthProducer/OAuthProducer.csproj
examples/Producer/Producer.csproj
examples/TlsAuth/TlsAuth.csproj
examples/Web/Web.csproj
src/Confluent.Kafka/Config_gen.cs
src/Confluent.Kafka/Confluent.Kafka.csproj

What
----
Checklist
References
----------
JIRA: 
Test & Review
------------

v2.10.1-RC1

---

README.md
examples/AdminClient/AdminClient.csproj
examples/Configuration/Configuration.csproj
examples/ConfluentCloud/ConfluentCloud.csproj
examples/Consumer/Consumer.csproj
examples/ExactlyOnce/ExactlyOnce.csproj
examples/ExactlyOnceOldBroker/ExactlyOnceOldBroker.csproj
examples/MultiProducer/MultiProducer.csproj
examples/OAuthConsumer/OAuthConsumer.csproj
examples/OAuthOIDC/OAuthOIDC.csproj
examples/OAuthProducer/OAuthProducer.csproj
examples/Producer/Producer.csproj
examples/TlsAuth/TlsAuth.csproj
examples/Web/Web.csproj
src/Confluent.Kafka/Config_gen.cs
src/Confluent.Kafka/Confluent.Kafka.csproj

What
----
Checklist
References
----------
JIRA: 
Test & Review
------------

Confluent.Kafka v2.10.1

---

src/Confluent.SchemaRegistry.Serdes.Avro/GenericSerializerImpl.cs
src/Confluent.SchemaRegistry.Serdes.Avro/SpecificSerializerImpl.cs
src/Confluent.SchemaRegistry.Serdes.Json/JsonSerializer.cs
src/Confluent.SchemaRegistry.Serdes.Protobuf/ProtobufSerializer.cs

What
----
Fix normalize parameter when looking up schemas
Checklist
- [Y] Contains customer facing changes? Including API/behavior changes 
- [Y] Did you add sufficient unit test and/or integration test coverage for this PR?
- covered by existing tests
References
----------
JIRA: 
Test & Review
------------

Fix normalize parameter when looking up schemas

---

src/Confluent.Kafka/Confluent.Kafka.csproj

What
----
Bump System.Memory to 4.6.3. 
Checklist
* No
* Not required — behavior remains unchanged and is already covered.
cc: @rayokota

Bump System.Memory to 4.6.3

---

.semaphore/semaphore.yml

What
----
This changes the macOS Semaphore job to use ARM instead of AMD. This is 40% cheaper.
Checklist
References
----------
JIRA: 
Test & Review
------------
PR checks

change to ARM macOS Semaphore agent

---

src/Confluent.SchemaRegistry.Serdes.Protobuf/DecimalExtensions.cs

What
----
This PR optimizes the conversion between .NET decimals and Protobuf decimals by leveraging the latest API features and eliminating unnecessary heap allocations.
Before
| Method                      | Mean     | Error   | StdDev  | Gen0   | Allocated |
|---------------------------- |---------:|--------:|--------:|-------:|----------:|
| Benchmark_ToProtobufDecimal | 120.2 ns | 0.26 ns | 0.21 ns | 0.1376 |     288 B |
| Benchmark_ToSystemDecimal   | 183.7 ns | 0.31 ns | 0.28 ns | 0.1566 |     328 B |
After 
| Method                      | Mean      | Error    | StdDev   | Gen0   | Allocated |
|---------------------------- |----------:|---------:|---------:|-------:|----------:|
| Benchmark_ToProtobufDecimal |  44.91 ns | 0.692 ns | 0.647 ns | 0.0650 |     136 B |
| …

Optimize Proto decimal conversion

---

src/Confluent.SchemaRegistry.Encryption.Aws/Confluent.SchemaRegistry.Encryption.Aws.csproj
src/Confluent.SchemaRegistry.Encryption.Azure/Confluent.SchemaRegistry.Encryption.Azure.csproj
src/Confluent.SchemaRegistry.Encryption.Gcp/Confluent.SchemaRegistry.Encryption.Gcp.csproj
src/Confluent.SchemaRegistry.Encryption.HcVault/Confluent.SchemaRegistry.Encryption.HcVault.csproj
src/Confluent.SchemaRegistry.Encryption.HcVault/HcVaultKmsClient.cs
src/Confluent.SchemaRegistry.Encryption/Confluent.SchemaRegistry.Encryption.csproj
src/Confluent.SchemaRegistry.Encryption/Cryptor.cs
src/Confluent.SchemaRegistry.Serdes.Avro/Confluent.SchemaRegistry.Serdes.Avro.csproj
src/Confluent.SchemaRegistry.Serdes.Json/Confluent.SchemaRegistry.Serdes.Json.csproj
src/Confluent.SchemaRegistry.Serdes.Protobuf/Confluent.SchemaRegistry.Serdes.Protobuf.csproj
src/Confluent.SchemaRegistry/Confluent.SchemaRegistry.csproj

What
----
Support CSFLE with .NET Framework 4.6.2+
Checklist
- [N] Contains customer facing changes? Including API/behavior changes 
- [N/A] Did you add sufficient unit test and/or integration test coverage for this PR?
References
----------
JIRA: 
Test & Review
------------

Support CSFLE with .NET Framework 4.6.2+

---

src/Confluent.SchemaRegistry.Encryption/KmsClientWrapper.cs

What
----
Checklist
References
----------
JIRA: 
Test & Review
------------

Fix encryption library build for net462

---

src/Confluent.SchemaRegistry.Serdes.Json/JsonUtils.cs
test/Confluent.SchemaRegistry.Serdes.UnitTests/JsonSerializeDeserialize.cs

What
----
Fix transformation of union of JSON refs
Checklist
- [Y] Contains customer facing changes? Including API/behavior changes 
- [Y] Did you add sufficient unit test and/or integration test coverage for this PR?
References
----------
JIRA: 
Test & Review
------------

DGS-22343 Fix transformation of union of JSON refs
