confluentinc/confluent-kafka-dotnet

- src/Confluent.Kafka/Consumer.cs
- src/Confluent.Kafka/Impl/SafeConfigHandle.cs
- src/Confluent.Kafka/Impl/SafeKafkaHandle.cs
- src/Confluent.Kafka/Impl/SafeTopicConfigHandle.cs
- src/Confluent.Kafka/Producer.cs
- test/Confluent.Kafka.IntegrationTests/Tests/GarbageCollect.cs
Fixes issue #27.
I have open questions still. Mostly, is there really any value in using SafeHandle to wrap unmanaged config pointers?
1. we don't want ownership semantics (a major service they provide). Also, the resource referenced is just memory allocated by librdkafka (not a win32 handle or anything like that). Does that make all of the advantages noted in https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.safehandle(v=vs.110).aspx irrelevant? 
2. we're grabbing the associated IntPtr and passing it into many of the librdkafka methods anyway (should we change the marshaling of methods like conf_set_error_cb take SafeHandle, not IntPtr ?)
I propose getting this fix in now and deferring careful consideration of the above and related questions to another Issue. At …
> no longer release config handles

- src/Confluent.Kafka/IDeliveryHandler.cs
- src/Confluent.Kafka/Impl/SafeKafkaHandle.cs
- src/Confluent.Kafka/Structs/GroupInfo.cs
- test/Confluent.Kafka.IntegrationTests/Tests/ListGroup.cs
Fixes issue: #34 as suggested by @bschmidtbauer 
Note: `GroupInfo` is now a class, not a struct which allows `ListGroup` to return `null` if the group doesn't exist.
TODO: as part of this PR let's re-consider whether any of our other structs would be better off as classes (almost certainly yes). https://msdn.microsoft.com/en-us/library/ms229017.aspx 
Also re-think organization of files (struct folder is getting less appropriate).
Also: are `QueryGroup` and `QueryGroups` better names for methods `ListGroup` and `ListGroups`? (is `ListGroup` a bit wrong?). The 'Query' names would be consistent with `QueryWatermarkOffsets`. A problem with this idea is the corresponding function in librdkafka is list_groups. So maybe `QueryGroup` and `ListGroups`? don't like the inconsistency. I guess the …
> Fixed: ListGroup throws exception if group doesn't exist

- src/Confluent.Kafka/ISerializingProducer.cs
- src/Confluent.Kafka/Producer.cs
Advantages:
1. default parameter values suffer from issues outlined here: http://haacked.com/archive/2010/08/10/versioning-issues-with-optional-arguments.aspx/ also see @tomasdeml and @bschmidtbauer comments in #39
2. `Nullable` is avoided for the timestamp and partition parameters (no value is specified implicitly via the chosen overload). I think this is definitely a good interface in the partition case because at any particular point of calling ProduceAsync, the user is very unlikely to want to specify a partition some of the time and 'unassigned' the rest of the time. It's more likely they may want to specify null timestamps intermixed with actual timestamps, but I would still expect such scenarios to be very rare.
Disadvantages
1. Lots repetition (however, users of .NET BCLs are used …
> ProduceAsync default params -> method overloads

- src/Confluent.Kafka/CommittedOffsets.cs
- src/Confluent.Kafka/Consumer.cs
- src/Confluent.Kafka/Error.cs
- src/Confluent.Kafka/ErrorCode.cs
- src/Confluent.Kafka/Impl/SafeKafkaHandle.cs
- src/Confluent.Kafka/Library.cs
- src/Confluent.Kafka/Producer.cs
- test/Confluent.Kafka.IntegrationTests/Tests/AssignOverloads.cs
- test/Confluent.Kafka.IntegrationTests/Tests/AssignPastEnd.cs
- test/Confluent.Kafka.IntegrationTests/Tests/DeserializingConsumer_Background.cs
- test/Confluent.Kafka.IntegrationTests/Tests/DeserializingConsumer_Poll.cs
- test/Confluent.Kafka.IntegrationTests/Tests/DuplicateConsumerAssign.cs
- test/Confluent.Kafka.IntegrationTests/Tests/GarbageCollect.cs
- test/Confluent.Kafka.IntegrationTests/Tests/ListGroup.cs
- test/Confluent.Kafka.IntegrationTests/Tests/NullVsEmpty.cs
- test/Confluent.Kafka.IntegrationTests/Tests/OnLog.cs
- test/Confluent.Kafka.IntegrationTests/Tests/OnPartitionsAssignedNotSet.cs
- test/Confluent.Kafka.IntegrationTests/Tests/ProduceTimestamp.cs
- test/Confluent.Kafka.IntegrationTests/Tests/SimpleProduceConsume.cs
- test/Confluent.Kafka.IntegrationTests/Tests/WatermarkOffsets.cs
- test/Confluent.Kafka.UnitTests/CommittedOffsets.cs
- test/Confluent.Kafka.UnitTests/Error.cs
- test/Confluent.Kafka.UnitTests/GroupInfo.cs
- test/Confluent.Kafka.UnitTests/Message.cs
- test/Confluent.Kafka.UnitTests/PartitionMetadata.cs
- test/Confluent.Kafka.UnitTests/TopicMetadata.cs
- test/Confluent.Kafka.UnitTests/TopicPartitionOffsetError.cs
Leading underscores on enum values are not CLS compliant so I've prefixed local ErrorCode values with RD_ instead. Alternatives are prefixing with L_ or LOCAL_ (and broker error codes with B_ or BROKER_), or just removing the underscore altogether.
prefixing with RD_ is my preferred option, but I don't like any of them to be honest. Seeking the opinion of others.
(and yes, whoops, accidentally pushed this branch to the confluentinc repo, not my own).
> making CLS compliant

- test/Confluent.Kafka.IntegrationTests/Tests/AssignOverloads.cs
this blocks indefinitely causing tests to hang.
I believe that is actually intended operation given current implementation.
> not subscribed, don't commit offsets

- doc/docfx.json
- doc/template/partials/navbar.tmpl.partial
- doc/toc.yml
@aayars - post release i guess.
This PR (I'm 90% sure) will ensure docfx makes API docs that are suitable to be placed in any path (links are all relative, and don't reference 'up' the tree). html files will be all under api/.. i.e. we'll have:
http://docs.confluent.io/[version]/clients/confluent-kafka-dotnet/api/Conflunet.Kafka.html
.css etc are one level up from api. it might be better to not have the 'api' component in the path, but i couldn't easily see how to make docfx do that.
> tweaks to docfx api doc generation

- .travis.yml
- test/Confluent.Kafka.UnitTests/Confluent.Kafka.UnitTests.csproj
The unit tests were only run under .net core, we should run them under netframework too.
We can only use net452+ due to xunit reference, better than nothing
VS2017 is buggy when multiple frameworks are used for now and tests won't be discovered anymore in the test explorer (because of multiple frameworks). They can still be run from CLI though so not an issue
I don't know how integration tests / benchmarking are run on confluent side so only included the unit tests
Also removed the sed in travis CI, it's not necessary now that we have the frawmeork specified when building/testing (and it would prevent the restore with the changes in Kafka.UnitTests)
> Run unit tests under standard net framework

- src/Confluent.Kafka/ISerializingProducer.cs
- src/Confluent.Kafka/Producer.cs
- test/Confluent.Kafka.IntegrationTests/Tests/OnLog.cs
Events should come from Producer only. If we create multiple serializedProducer, we don't want to duplicates the log/stats/error (we have only one producer instance and can't know from which Serializingproducer the error came)
Also the constructors made a subscription on Producer.OnLog, thus not logging anything in console when no callbacks were made
Producer<K,V> keeps the events as it create a Producer instance, but events are now just mapped to the Producer instance rather than making an intermediate subscription (same reasons as before)
> Remove events from SerializingProducer

- src/Confluent.Kafka/Impl/LibRdKafka.cs
Fix #115 : make 0.9.4 as min version (for producev even if it's not used for now)
We may want to have fallbacks, but for now this will help to not have people targeting Internal.Rdkafka 0.9.1 I think only 0.9.2 is a minimum for now (with flush). Perhaps we could add an attribute on each method in NativeMethods to say what is the minimal supported version and what version are deprecated (for example due to a bug) We could then parse them all when starting given the version loaded and provide some logs on this. This would be an other enhancement though
Fix #145 #72 : now load with LoadLibraryEx with a custom flag so that dependencies are searched in the same folder (this was not the case for msvcr120.dll) Also throw a more meaningful exception
> Fix loading of librdkafka dependencies in .NET Framework 

- src/Confluent.Kafka/Consumer.cs
- src/Confluent.Kafka/Impl/SafeKafkaHandle.cs
Removed redundant `await`'s and `async` modifiers:
- There is no need to await call results, if they are not used in the continuation. Methods will be awaited by the caller. Also removing `async` modifier allows to gain some additional performance, since the compiler now won't generate state machines for these methods.
- Library code anyway shouldn't capture client's synchronization context ([details](https://channel9.msdn.com/Series/Three-Essential-Tips-for-Async/Async-library-methods-should-consider-using-Task-ConfigureAwait-false-)).
> Remove redundant awaits

- .travis.yml
Now that curl is fixed on travis-osx for .net core, there shouldn't be any more random error on build
> Fix" Too many open files" in travis osx

- examples/Misc/Program.cs
- examples/MultiProducer/Program.cs
- examples/SimpleConsumer/Program.cs
- examples/SimpleProducer/Program.cs
- src/Confluent.Kafka/Consumer.cs
- src/Confluent.Kafka/Producer.cs
- test/Confluent.Kafka.Benchmark/BenchmarkConsumer.cs
- test/Confluent.Kafka.Benchmark/BenchmarkProducer.cs
- test/Confluent.Kafka.IntegrationTests/Tests/AssignOverloads.cs
- test/Confluent.Kafka.IntegrationTests/Tests/AssignPastEnd.cs
- test/Confluent.Kafka.IntegrationTests/Tests/DuplicateConsumerAssign.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Metadata.cs
- test/Confluent.Kafka.IntegrationTests/Tests/NullVsEmpty.cs
- test/Confluent.Kafka.IntegrationTests/Tests/OnLog.cs
- test/Confluent.Kafka.IntegrationTests/Tests/OnPartitionsAssignedNotSet.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Producer_ProduceAsync_DeliveryHandler.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Producer_ProduceAsync_Null_DeliveryHandler.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Producer_ProduceAsync_Null_Task.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Producer_ProduceAsync_Task.cs
- test/Confluent.Kafka.IntegrationTests/Tests/SerializingProducer_ProduceAsync_DeliveryHandler.cs
- test/Confluent.Kafka.IntegrationTests/Tests/SerializingProducer_ProduceAsync_Null_DeliveryHandler.cs
- test/Confluent.Kafka.IntegrationTests/Tests/SerializingProducer_ProduceAsync_Null_Task.cs
- test/Confluent.Kafka.IntegrationTests/Tests/SerializingProducer_ProduceAsync_Task.cs
- test/Confluent.Kafka.IntegrationTests/Tests/SimpleProduceConsume.cs
- test/Confluent.Kafka.IntegrationTests/Tests/WatermarkOffsets.cs
- test/Confluent.Kafka.IntegrationTests/Util.cs
- test/Confluent.Kafka.VerifiableClient/Program.cs
@treziac @edenhill @ewencp 
People who use variants of these methods with an infinite timeout usually don't realize they can't cancel out of them or even that they generally might want to - better if they don't exist.
Actually we should add variants that take a `CancellationToken` as well, but that can happen in a latter PR.
> Obsoleting or removing methods that can potentially block indefinitely

- src/Confluent.Kafka/Confluent.Kafka.csproj
- src/Confluent.Kafka/Impl/LibRdKafka.cs
- src/Confluent.Kafka/Producer.cs
- test/Confluent.Kafka.IntegrationTests/Tests/DeserializingConsumer_Poll_Error.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Producer_ProduceAsync_Await.cs
- test/Confluent.Kafka.IntegrationTests/Tests/SerializingProducer_ProduceAsync_Await.cs
This is a quick fix for #92.
The performance hit is unfortunately very high - scheduling on the thread pool results in a 4x slow down compared to the `IDeliveryHandler` variants of `ProduceAsync` (as @ah- warned).
I'm wondering if there is a way of solving this on the poll loop side of things - some fancy dual-thread arrangement or something (but i'm a bit wary - it's less straightforward to analyse).
finally: the tests actually work even without the fix in place for some reason. I haven't tried to work out why. I've verified the fix is effective in a console app.
Considering this a Work-In-Progress - putting it out there as a start.
> [WIP] Call SetResult on threadpool for Task ProduceAsync variants

- src/Confluent.Kafka/Impl/SafeKafkaHandle.cs
Fix for bug found in #220 @treziac @chiru1205
> memberId: IntPtr == null -> IntPtr == IntPtr.Zero

- examples/SimpleProducer/Program.cs
- src/Confluent.Kafka/Consumer.cs
- src/Confluent.Kafka/Internal/Extensions/String.cs
- src/Confluent.Kafka/Internal/Extensions/TimeSpan.cs
- src/Confluent.Kafka/Producer.cs
- src/Confluent.Kafka/Serialization/Extensions/Message.cs
- src/Confluent.Kafka/Serialization/IDeserializer.cs
- src/Confluent.Kafka/Serialization/ISerializer.cs
- src/Confluent.Kafka/Serialization/IntDeserializer.cs
- src/Confluent.Kafka/Serialization/IntSerializer.cs
- src/Confluent.Kafka/Serialization/LongDeserializer.cs
- src/Confluent.Kafka/Serialization/LongSerializer.cs
- src/Confluent.Kafka/Serialization/NullDeserializer.cs
- src/Confluent.Kafka/Serialization/NullSerializer.cs
- src/Confluent.Kafka/Serialization/StringDeserializer.cs
- src/Confluent.Kafka/Serialization/StringSerializer.cs
- src/Confluent.Kafka/include_docs.xml
- test/Confluent.Kafka.UnitTests/IntSerde.cs
- test/Confluent.Kafka.UnitTests/Serialization/Long.cs
- test/Confluent.Kafka.UnitTests/Serialization/String.cs
alternative to #202, following on from #129 
I like this better. Similar to Java, except (de)serializers specified via constructors can be configured using the config passed into the `Producer` or `Consumer`.
> serialization API rework

- src/Confluent.Kafka/Error.cs
- src/Confluent.Kafka/TopicPartition.cs
- src/Confluent.Kafka/TopicPartitionOffset.cs
- src/Confluent.Kafka/TopicPartitionOffsetError.cs
- test/Confluent.Kafka.UnitTests/Error.cs
- test/Confluent.Kafka.UnitTests/TopicPartition.cs
- test/Confluent.Kafka.UnitTests/TopicPartitionOffset.cs
- test/Confluent.Kafka.UnitTests/TopicPartitionOffsetError.cs
Prevent NullReferenceException when doing == or != comparisons when Kafka object is null.
> Handle null object case in equality operator overrides.

- src/Confluent.Kafka/Producer.cs
there has been plenty of feedback that people want the non-serializing producer, e.g. #116, so removing the UNSTABLE designation. @ewencp
> removing UNSTABLE designation from non-serializing Producer

- src/Confluent.Kafka/Impl/SafeKafkaHandle.cs
- test/Confluent.Kafka.UnitTests/InvalidHandle.cs
Fix #125 
Not sure how to test given ssl configuration, but I can with providing a null socket_cb for example to test when rd_kafka_create fail.
> WIP: Fix Accessviolation when handler creation fails

- test/Confluent.Kafka.IntegrationTests/Tests/DeserializingConsumer_Poll_Error.cs
- test/Confluent.Kafka.IntegrationTests/Tests/OnPartitionsAssignedNotSet.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Producer_ProduceAsync_Await.cs
- test/Confluent.Kafka.IntegrationTests/Tests/SerializingProducer_ProduceAsync_Await.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Tests.cs
Fix #136 
Fix integration tests on windows (path to file and bug on Console.Error)
Also fix integration tests when testing on distant cluster, where flush/poll need more time to complete properly
> Fix integration test on windows and/or distant cluster

- src/Confluent.Kafka/Serialization/ByteArrayDeserializer.cs
- src/Confluent.Kafka/Serialization/ByteArraySerializer.cs
- src/Confluent.Kafka/Serialization/DoubleDeserializer.cs
- src/Confluent.Kafka/Serialization/DoubleSerializer.cs
- src/Confluent.Kafka/Serialization/FloatDeserializer.cs
- src/Confluent.Kafka/Serialization/FloatSerializer.cs
- test/Confluent.Kafka.UnitTests/BrokerMetadata.cs
- test/Confluent.Kafka.UnitTests/CommittedOffsets.cs
- test/Confluent.Kafka.UnitTests/Consumer.cs
- test/Confluent.Kafka.UnitTests/Error.cs
- test/Confluent.Kafka.UnitTests/GroupInfo.cs
- test/Confluent.Kafka.UnitTests/GroupMemberInfo.cs
- test/Confluent.Kafka.UnitTests/InvalidHandle.cs
- test/Confluent.Kafka.UnitTests/LogMessage.cs
- test/Confluent.Kafka.UnitTests/Message.cs
- test/Confluent.Kafka.UnitTests/Metadata.cs
- test/Confluent.Kafka.UnitTests/Offset.cs
- test/Confluent.Kafka.UnitTests/PartitionMetadata.cs
- test/Confluent.Kafka.UnitTests/Serialization/ByteArray.cs
- test/Confluent.Kafka.UnitTests/Serialization/Double.cs
- test/Confluent.Kafka.UnitTests/Serialization/Float.cs
- test/Confluent.Kafka.UnitTests/Serialization/Int.cs
- test/Confluent.Kafka.UnitTests/Serialization/Long.cs
- test/Confluent.Kafka.UnitTests/Serialization/String.cs
- test/Confluent.Kafka.UnitTests/Timestamp.cs
- test/Confluent.Kafka.UnitTests/TopicMetadata.cs
- test/Confluent.Kafka.UnitTests/TopicPartition.cs
- test/Confluent.Kafka.UnitTests/TopicPartitionOffset.cs
- test/Confluent.Kafka.UnitTests/TopicPartitionOffsetError.cs
- test/Confluent.Kafka.UnitTests/WatermarkOffsets.cs
this is a continuation of @wangyanjun 's  #130. Adds `double` serde + updates for new serialization interface.
> byte[], float and double serdes

- README.md
added a badge that links to the clients confluent community slack channel. 
should do this for the other clients too.
> added badge for slack

- src/Confluent.Kafka/Consumer.cs
The `Consume` method has now proven it's self useful in a number of scenarios in which the `Poll` method is inconvenient. we should definitely keep both.
@edenhill
> Removed unstable designation from Consume method

- README.md
- appveyor.yml
appveyor exposes pre-release nuget packages, so let's just point people to that and not bother uploading pre-release versions to nuget.org.
for now, leaving the task of uploading release versions to nuget.org as a manual process.
> AppVeyor pre-release nuget feed

- README.md
- examples/AdvancedConsumer/AdvancedConsumer.csproj
- examples/AdvancedProducer/AdvancedProducer.csproj
- examples/FSharp/FSharp.fsproj
- examples/Misc/Misc.csproj
- examples/MultiProducer/MultiProducer.csproj
- examples/SimpleConsumer/SimpleConsumer.csproj
- examples/SimpleProducer/SimpleProducer.csproj
- src/Confluent.Kafka/Confluent.Kafka.csproj
- test/Confluent.Kafka.Benchmark/Confluent.Kafka.Benchmark.csproj
- test/Confluent.Kafka.IntegrationTests/Confluent.Kafka.IntegrationTests.csproj
- test/Confluent.Kafka.StrongName.UnitTests/Confluent.Kafka.StrongName.UnitTests.csproj
- test/Confluent.Kafka.UnitTests/Confluent.Kafka.UnitTests.csproj
- test/Confluent.Kafka.VerifiableClient/Confluent.Kafka.VerifiableClient.csproj
@edenhill - as discussed. unfortunately this will fail with a non-descriptive exception if people don't reference librdkafka.redist. I don't think it's easy to give a better warning until the SSL dependency related changes go in. I'll test again on all platforms before tagging and deploying to nuget.
> removed librdkafka.redist dependency. added note to readme

- src/Confluent.Kafka/Producer.cs
`TaskCompletionSource` class has [4 constructors](https://msdn.microsoft.com/en-us/library/dd449174(v=vs.110).aspx), and there is no constructor with `TaskContinuationOptions` parameter.
Obviously, it's a simple typo because both `TaskContinuationOptions` and `TaskCreationOptions` enums have the same values. So 
```csharp
private sealed class TaskDeliveryHandler : TaskCompletionSource<Message>, IDeliveryHandler
{
public TaskDeliveryHandler() : base(TaskContinuationOptions.RunContinuationsAsynchronously)
{
}
```
it should be
```csharp
private sealed class TaskDeliveryHandler : TaskCompletionSource<Message>, IDeliveryHandler
{
public TaskDeliveryHandler() : base(TaskCreationOptions.RunContinuationsAsynchronously)
{
}
```
> Replace TaskContinuationOptions with TaskCreationOptions in DeliveryHandler constructor

- src/Confluent.Kafka/Producer.cs
@edenhill - fix for #412. 
This new functionality follows the example in: https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/task-cancellation 
I don't actually understand why the existing way of doing this is causing intermittent problems, however it doesn't matter as the new way is valid, and avoids the problem.
> use ThrowIfCancellationRequested to exit producer poll loop

- src/Confluent.Kafka/Confluent.Kafka.csproj
- src/Confluent.Kafka/Impl/SafeKafkaHandle.cs
- src/Confluent.Kafka/Internal/Util.cs
- src/Confluent.Kafka/Producer.cs
Below are the results of measurements for  10 iterations per 10 mln. messages.
All values are in `msg/ms`.
`test\Confluent.Kafka.Benchmark` project was used for benchmarking.
  | average | median | std. dev
-- | -- | -- | --
produce (original) | 773,6 | 780 | 21,25653
produce (patched) | 796,8 | 805 | 20,33126
consume (original) | 548,9 | 552 | 9,658675
consume (patched) | 1722,6 | 1723 | 4,127953
poll (original) | 428,1 | 421 | 42,88461
poll (patched) | 1668,9 | 1675,5 | 28,72786
Here is a quick recap of the data above based on median values:
  | original (msg/ms) | patched (msg/ms) |  
-- | -- | -- | --
produce | 780 (+-21) | 805 (+-20) | ? might be 1.03x faster
poll | 421 (+-43) | 1675 (+-29) | ^ definitely 3.98x faster
consume | 552 (+-10) | 1723 (+-4) | ^ definitely 3.12x faster …
> Structs and strings marshaling performance optimization

- src/Confluent.Kafka/Consumer.cs
@edenhill - I wanted this when writing a test. I think it's better to have convenience overloads like this than not, even though this particular case is probably not that commonly needed.
> added single partition overloads for Assign

- src/Confluent.Kafka/Producer.cs
a problem introduced in #413 - the exception used to exit the while loop should be caught, it is not.
> handle OperationCanceledException

- README.md
- src/Confluent.Kafka/ConsumerRecord.cs
- src/Confluent.Kafka/ConsumerRecord_KV.cs
- src/Confluent.Kafka/DeliveryReport.cs
- src/Confluent.Kafka/DeliveryReport_KV.cs
- src/Confluent.Kafka/MessageAndMeta.cs
- src/Confluent.Kafka/MessageAndMeta_KV.cs
This commit addresses the two deficiencies noted in the comments of the preceding PR - duplication of code between `ConsumerRecord` and `DeliveryReport` and the fact that `Message` is only nested but `TopicPartitionOffsetError` both is.. and isn't. I think it's convenient and makes a lot of structural sense to have everything both flattened and nested.
> MessageAndMeta, flattened & nested.

- src/Confluent.Kafka/Consumer.cs
- src/Confluent.Kafka/Producer.cs
- test/Confluent.Kafka.UnitTests/Consumer.cs
- test/Confluent.Kafka.UnitTests/Producer.cs
Recently, we provoked a generic NullReferenceException by accidentally passing a `null` value as configuration to the consumer constructor which took us some time to identify the parameter causing the trouble.
Therefore, this PR suggests to apply validation to the configuration passed to consumers and producers, checking all key-value-pairs' values for not null. In case the validation fails, an ArgumentExcpetion is thrown containing the configuration key name to make debugging more easy.
I've implemented the validation for the `1.0-experimental` branch. However - if more appropriate - I can supply the patch for another branch as well.
Looking forward to your feedback!
> Validate config values for 'not-null'

- src/Confluent.Kafka/Consumer.cs
- src/Confluent.Kafka/Producer.cs
- test/Confluent.Kafka.UnitTests/Consumer.cs
- test/Confluent.Kafka.UnitTests/Producer.cs
Same feature as #543, cherry-picked to `master`.
> Validate config values for 'not-null' (on `master`)

- src/Confluent.Kafka/Offset.cs
- src/Confluent.Kafka/Partition.cs
- src/Confluent.Kafka/Timestamp.cs
Micro-optimization to avoid boxing when comparing structs (Partition, Offset, and Timestamp). I noticed it when using TopicPartition as the key to a dictionary. `EqualityComparer<T>.Default` checks if a type implements IEquatable<T> and uses it if present, so this also helps the dictionary case when a custom equality comparer isn't used.
Here is a before/after micro benchmark
```
Method |      Mean |     Error |    StdDev |  Gen 0 | Allocated |
-------------------------- |----------:|----------:|----------:|-------:|----------:|
PartitionEquals |  5.276 ns | 0.0350 ns | 0.0310 ns | 0.0076 |      24 B |
PartitionEqualityComparer |  5.555 ns | 0.0258 ns | 0.0228 ns | 0.0076 |      24 B |
PartitionDictionary | 10.575 ns | 0.0326 ns | 0.0304 ns | 0.0076 |      24 B |
Method |      Mean | …
```
> Implement IEquatable on structs to avoid equality boxing

- src/Confluent.Kafka/Impl/LibRdKafka.cs
As librdkafka DLLs are getting dumped into bin/debug folder, in some cases, an attempt to get them from baseDirectory.
> librdkafka directory path fix

- README.md
quick cleanup. most importantly, the namespace `Confluent.Kafka.Serialization` actually no longer exists, so the examples on the README.md won't compile as is.
> example code cleanup

- src/Confluent.Kafka/Producer.cs
Typo.  Should be 'delivery' instead of 'delievery'
> fix typo in comment doc

- test/Confluent.Kafka.IntegrationTests/Tests/Headers.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Producer_BeginProduce.cs
Integration tests that have checks related to delivery report order following `BeginProduce` calls - where order should be preserved - are intermittently failing. This is a long standing issue. This could be explained by messages delivery failure and retries, though this does seem unlikely in the context of local broker integration tests. Never-the-less, I've enabled idempotence on these tests in this PR, which I believe should ensure delivery report order is the same as produce order in the event of delivery failure [though I wasn't able to find good docs to confirm this - the reviewer should know :-) ]. Alternatively, I could set `message.send.max.retries` to 0, though the tests would still fail in the above scenario due to message failure (but the change would still be an improvement …
> enable idempotence on integration tests where dr order is important

- CHANGELOG.md
- examples/AvroBlogExamples/Program.cs
- examples/ConfluentCloud/Program.cs
- examples/Consumer/Program.cs
- examples/Protobuf/Program.cs
- src/ConfigGen/Program.cs
- src/Confluent.Kafka/Config.cs
- src/Confluent.Kafka/Config_gen.cs
- src/Confluent.Kafka/Confluent.Kafka.csproj
- src/Confluent.Kafka/Partition.cs
- test/Confluent.Kafka.IntegrationTests/Tests/AssignPastEnd.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Consumer_Pause_Resume.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Consumer_StoreOffsets.cs
- test/Confluent.Kafka.StrongName.UnitTests/Confluent.Kafka.StrongName.UnitTests.csproj
- test/Confluent.Kafka.UnitTests/ConfigEnums.cs
- test/Confluent.Kafka.UnitTests/InvalidHandle.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests/AutoRegisterSchemaDisabled.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests/AvroAndRegular.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests/ConsumeIncompatibleTypes.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests/ConsumePartitionEOF.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests/PrimitiveTypes.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests/ProduceConsume.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests/ProduceIncompatibleTypes.cs
- Audited all the enum types in Confluent.Kafka for compliance with .net naming standards and made appropriate changes.
- Changed the `acks` configuration parameter to an enum (of type int32). Note that it's valid in C# to set an enum type to a value that isn't one of it's discrete names (e.g. Acks = 2), so i think this has precisely the semantics we want, also when considering possible future requirements.
@edenhill @rnpridgeon
> various enum related changes

- src/Confluent.SchemaRegistry/Rest/RestService.cs
- test/Confluent.SchemaRegistry.IntegrationTests/Tests/Failover.cs
resolves #711 
verified manually - we should add tests for this case, but that would complicate the dependencies required (an additional SR instance) making it less trivial to start up. we should do this, but after or as part of the task to automate execution of the integration tests. i'll add an issue to track this.
The problem was `HttpClient` doesn't allow the same request instance to be sent more than once. I don't like this behavior TBH. One of a growing number of things I don't like about `HttpClient`.
> fixed failover connection issue

- examples/Consumer/Program.cs
- src/Confluent.Kafka/Consumer.cs
- src/Confluent.Kafka/ConsumerBase.cs
- src/Confluent.Kafka/IConsumer.cs
- src/Confluent.Kafka/IConsumerBase.cs
also changed the return types to `void`, as returning something effectively provided by the user was pretty pointless and for consistency with the base method used to implement.
> Moved ConsumeResult Commit methods to correct place

- src/Confluent.Kafka/IDeliveryHandler.cs
- src/Confluent.Kafka/Producer.cs
the last thing I did before opening #760 was make `IDeliveryHandler` a child class of `Producer<K,V>`. In doing this, I neglected to consider the fact that this generates a new `IDeliveryHandler` type for each producer K,V, breaking an assumption that this is not the case by the dependent producer implementation. didn't realize this at the time because I didn't re-run the integration tests because this was such a simple change it couldn't possibly have gone wrong.
> fix regression introduced in #760

- src/Confluent.Kafka/Admin/AlterConfigsException.cs
- src/Confluent.Kafka/Admin/CreatePartitionsException.cs
- src/Confluent.Kafka/Admin/CreateTopicsException.cs
- src/Confluent.Kafka/Admin/DeleteTopicsException.cs
- src/Confluent.Kafka/Admin/DescribeConfigsException.cs
- src/Confluent.Kafka/Exceptions/TopicPartitionException.cs
- src/Confluent.Kafka/Exceptions/TopicPartitionOffsetException.cs
it's useful for these exception types to have a base class `KafkaException` since the user may not care about the details of the problem, and this allows these exceptions to be caught in the same handler as other librdkafka generated exceptions.
the `Local_` prefix is a bit misleading, but i think this is ok.
this pr is reverting the revert in #773 (but uses an appropriate error code).
> partital error exception types

- examples/AdminClient/AdminClient.csproj
- examples/AdminClient/Program.cs
- src/Confluent.Kafka/AdminClient.cs
Analogous to the `Producer`, care needs to be taken to ensure the `AdminClient`  doesn't deadlock on `Dispose` when it's methods are `await`ed. The strategy used by this PR to prevent this is the same as used in the .NET Framework case in the producer (which is to set the task result on a thread pool thread). .NET Core provides `TaskCreationOptions.RunContinuationsAsynchronously` which allows for a better solution, but I didn't bother complicating the `AdminClient` with this since performance isn't a concern here like it is with the producer.
Also did a minor iteration on the `AdminClient` example (which could do with even more work).
> fix AdminClient deadlock issue + improve AdminClient example

- src/Confluent.Kafka/AdminClient.cs
- src/Confluent.Kafka/Consumer.cs
- src/Confluent.Kafka/IAdminClient.cs
- src/Confluent.Kafka/IConsumer.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Producer_Handles.cs
- test/Confluent.Kafka.IntegrationTests/Tests/WatermarkOffsets.cs
Follows the java client and puts the query/get watermark functionality on the consumer where it is commonly needed rather than requiring a wrapper admin client. this change takes the query wm offsets capability away from being available on a librdkafka producer instance (via being wrapped by an admin client), but I don't think that's a common requirement. Since I can't think when this would be useful and the java producer doesn't provide similar functionality, I took the view that `QueryWatermarkOffsets` could be added back to `AdminClient` or to the `Producer` later if the need becomes clear (non-breaking change). For `GetWatermarkOffsets`, it was an especially questionable decision to effectively allow this to be called on a producer instance, since it favors runtime over compile …
> move get/query watermark offset methods to consumer

- src/Confluent.Kafka/DeliveryResult.cs
- src/Confluent.Kafka/Producer.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Producer_BeginProduce.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Producer_BeginProduce_Error.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Producer_BeginProduce_Null.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Producer_ProduceAsync_Error.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Producer_ProduceAsync_Task.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests/AutoRegisterSchemaDisabled.cs
Following @rnpridgeon in the python client, changed the name of `DeliveryResult.PersistenceStatus` to `DeliveryResult.Status`. I think this is better because:
1. the property and enum will always be used together in practice and it's more verbose than necessary to have the word persistence appear twice.
2. `PersistenceStatus` is a bit awkward sounding.
> PersistenceStatus -> Status + integration tests

- src/Confluent.Kafka/Confluent.Kafka.csproj
- src/Confluent.Kafka/Consumer.cs
- src/Confluent.Kafka/Internal/Util.cs
- src/Confluent.Kafka/Producer.cs
resolves #796 
the `PtrToStructureUnsafe` method is theoretically more efficient, but I'm not seeing a significant regression in performance by reverting to the less performant version (disclaimer: benchmark results are pretty noisy) and loosing the dependency on `System.Runtime.CompilerServices.Unsafe`.
> removed CompilerServices.Unsafe dependency

- CHANGELOG.md
- src/Confluent.Kafka/Producer.cs
- test/Confluent.Kafka.IntegrationTests/Tests/AddBroker.cs
- test/Confluent.Kafka.IntegrationTests/Tests/AdminClient_CreatePartitions.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Timestamps.cs
Over in #831, @BackTrak points out the `GetResult` call in the `ProduceAsync` call is problematic in some scenarios. This PR resolves that. 
The downside of doing this is that if `ProduceAsync` is used synchronously, an `AggregateException` is thrown with the actual exception exposed via `InnerException`, which is inconvenient. However, that reflects a limitation / annoying trad-off made in .NET, rather than something we should avoid here.
I've retained the `GetResult` in `BeginProduce` for now. We need to think carefully what we want to do there - I think we'll probably want `BeginProduceAsync` in addition to `BeginProduce`.
Also fixed a bug in the `AddBrokers` test (which I found due to now running integration tests against a 3 broker cluster).
> made ProduceAsync async

- src/Confluent.Kafka/Consumer.cs
- src/Confluent.Kafka/Producer.cs
`Consumer.Consume` and `Producer.BeginProduce` both block on async serdes. There was a deadlock problem with the previous implementation when used in a single threaded context (WinForms, WPF, WebAPI...). This PR forces async serdes to be run on a different thread (my understanding was that the previous implementation was supposed to do this, but it doesn't). All of this is considered an anti-pattern, but it is well considered and i believe appropriate here. Note: there are only performance implications for async serdes (i.e. currently just avro, which is slow anyway), and this is of similar order to doing async 'properly'. Justification of API:
- There is a fully legit async-all-the-way-down alternative `ProduceAsync`. This is most likely what people actually want when they're writing …
> run async serdes on thread pool thread

- src/Confluent.Kafka/AdminClient.cs
- src/Confluent.Kafka/Consumer.cs
- src/Confluent.Kafka/DeliveryResult.cs
- src/Confluent.Kafka/IAdminClient.cs
- src/Confluent.Kafka/IClient.cs
- src/Confluent.Kafka/IConsumer.cs
- src/Confluent.Kafka/IProducer.cs
- src/Confluent.Kafka/Producer.cs
1. move API doc comments from Producer / Consumer / AdminClient -> IProducer / IConsumer / IAdminClient . The builder classes return interfaces now, so this change makes intellisense useful again.
2. change line lengths of the comments so they display well in Visual Studio Code intellisense (which has a relatively narrow fixed width hover window, and honors new lines).
> comments: interface <-> class & formatting

- examples/AvroBlogExamples/Program.cs
- examples/Consumer/Program.cs
- examples/Protobuf/Program.cs
- src/Confluent.Kafka/Consumer.cs
- src/Confluent.Kafka/Deserializers.cs
- src/Confluent.Kafka/Producer.cs
- src/Confluent.Kafka/Serializers.cs
- test/Confluent.Kafka.IntegrationTests/Tests/AssignPastEnd.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Consumer_DisableHeaders.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Consumer_DisableTimestamps.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Consumer_OffsetsForTimes.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Consumer_Pause_Resume.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Consumer_Seek.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Consumer_StoreOffset.cs
- test/Confluent.Kafka.IntegrationTests/Tests/DuplicateConsumerAssign.cs
- test/Confluent.Kafka.IntegrationTests/Tests/GarbageCollect.cs
- test/Confluent.Kafka.IntegrationTests/Tests/LogDelegate.cs
- test/Confluent.Kafka.IntegrationTests/Tests/OnPartitionsAssignedNotSet.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Producer_BeginProduce_Error.cs
- test/Confluent.Kafka.UnitTests/Serialization/ByteArray.cs
- test/Confluent.Kafka.UnitTests/Serialization/Double.cs
- test/Confluent.Kafka.UnitTests/Serialization/Float.cs
- test/Confluent.Kafka.UnitTests/Serialization/Int.cs
- test/Confluent.Kafka.UnitTests/Serialization/Long.cs
- test/Confluent.Kafka.UnitTests/Serialization/String.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests/AvroAndRegular.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests/ConsumePartitionEOF.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests/ProduceConsumeGeneric.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests/ProduceGenericMultipleTopics.cs
this is seeming a bit superfluous now everything's housed in the `Serializers` and `Deserializer` static classes.
> removed Confluent.Kafka.Serdes namespace

- CHANGELOG.md
- README.md
- examples/AdminClient/AdminClient.csproj
- examples/AvroBlogExamples/AvroBlogExamples.csproj
- examples/AvroGeneric/AvroGeneric.csproj
- examples/AvroSpecific/AvroSpecific.csproj
- examples/ConfluentCloud/ConfluentCloud.csproj
- examples/Consumer/Consumer.csproj
- examples/MultiProducer/MultiProducer.csproj
- examples/Producer/Producer.csproj
- examples/Protobuf/Protobuf.csproj
- src/Confluent.Kafka/Confluent.Kafka.csproj
- src/Confluent.SchemaRegistry.Serdes/Confluent.SchemaRegistry.Serdes.csproj
- src/Confluent.SchemaRegistry/Confluent.SchemaRegistry.csproj
I accidentally versioned Confluent.SchemaRegistry.Serdes v1.0-R53 not 1.0-RC5. the other artifacts are already on nuget, the only non-hack thing we can do is -> RC6.
> -> 1.0-RC6

- src/Confluent.Kafka/DependentProducerBuilder.cs
This way of leveraging a single producer handle with different data types is flawed and also a bit inconvenient to use. this PR allows for the possibility for this to be solved properly in the future without a major version bump.
> added API-SUBJECT-TO-CHANGE notice

- examples/AvroBlogExamples/Program.cs
- examples/AvroGeneric/Program.cs
- examples/AvroSpecific/Program.cs
- src/Confluent.Kafka/SyncOverAsyncDeserializer.cs
- src/Confluent.Kafka/SyncOverAsyncSerializer.cs
- test/Confluent.Kafka.IntegrationTests/Serdes.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests/AvroAndRegular.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests/ConsumeIncompatibleTypes.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests/ConsumePartitionEOF.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests/PrimitiveTypes.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests/ProduceConsume.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests/ProduceConsumeGeneric.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests/SyncOverAsync.cs
it's not usual for library implementers to provide SyncOverAsync helper methods. our case is special though because we currently force people to do sync-over-async in order to use the consumer with the avro serializers. However, when we implement `ConsumeAsync`, we won't want people to do this, and we won't really want these extension methods visible to all who do `using Confluent.Kafka`. This PR moves SyncOverAsync functionality to it's own namespace, which is easy to ignore in the future, whilst not being too much of a burden to use now.
> moved all sync-over-async functionality to it's own namespace

- src/Confluent.Kafka/LogLevelType.cs
- src/Confluent.Kafka/LogMessage.cs
- test/Confluent.Kafka.UnitTests/LogMessage.cs
will need this for the blog post. your choice whether we slip it in before 1.0 (not a breaking api change). if not there will be a 1.0.1 immediately after.
> added LogLevelType and conversions

- src/Confluent.Kafka/Impl/LibRdKafka.cs
- src/Confluent.Kafka/Impl/NativeMethods/NativeMethods_Alpine.cs
Resolved #611 
Like CentOS and Debian, the native library needs to be loaded from `alpine-librdkafka.so` not `librdkafka.so`.
```
/app # ldd /app/runtimes/linux-x64/native/librdkafka.so
ldd (0x7f9189dcd000)
libm.so.6 => ldd (0x7f9189dcd000)
Error loading shared library libsasl2.so.2: No such file or directory (needed by /app/runtimes/linux-x64/native/librdkafka.so)
libssl.so.1.0.0 => /lib/libssl.so.1.0.0 (0x7f91897cc000)
libcrypto.so.1.0.0 => /lib/libcrypto.so.1.0.0 (0x7f91893ad000)
libz.so.1 => /lib/libz.so.1 (0x7f9189196000)
libdl.so.2 => ldd (0x7f9189dcd000)
libpthread.so.0 => ldd (0x7f9189dcd000)
librt.so.1 => ldd (0x7f9189dcd000)
libc.so.6 => ldd (0x7f9189dcd000)
Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by …
```
> add native methods from alpine-librdkafka.so

- CHANGELOG.md
- README.md
- examples/AdminClient/AdminClient.csproj
- examples/AvroBlogExamples/AvroBlogExamples.csproj
- examples/AvroGeneric/AvroGeneric.csproj
- examples/AvroSpecific/AvroSpecific.csproj
- examples/ConfluentCloud/ConfluentCloud.csproj
- examples/Consumer/Consumer.csproj
- examples/MultiProducer/MultiProducer.csproj
- examples/Producer/Producer.csproj
- examples/Protobuf/Protobuf.csproj
- src/Confluent.Kafka/Confluent.Kafka.csproj
- src/Confluent.SchemaRegistry.Serdes/Confluent.SchemaRegistry.Serdes.csproj
- src/Confluent.SchemaRegistry/Confluent.SchemaRegistry.csproj
@edenhill - i realize this numbering scheme for you is probably like looking at a font with the kerning off or something, but it's supported by nuget and there is precedent with other libraries, so let's give it a go.
the 1.0.1 implies librdkafka 1.0.1, allowing people easily refer to the correct librdkafka docs / release notes etc.
> -> v1.0.1.1

- test/Confluent.Kafka.Benchmark/BenchmarkConsumer.cs
quick win - this gives 5x throughput gain to > 1M msg/s on my localhost.
> make consumer benchmark 5x faster

- src/Confluent.SchemaRegistry/Rest/RestService.cs
fixes: https://github.com/confluentinc/confluent-kafka-dotnet/issues/993
> fix(Schema Registry): append '/' to `RestService.BaseAddress` and remove '/' from subject requests

- src/ConfigGen/Program.cs
- src/Confluent.Kafka/Config.cs
- src/Confluent.Kafka/Config_gen.cs
* delegate to base ctors
* simplify the creation of the kvp -> dictionary
* add ability to update a dictionary "in place"
Last one is handy for config validation, setting defaults etc in dotnetCore IOptions stuff
this is a replacement for #881 in that it _just_ reworks to ctors but does not add the KeyNames generation parts. Follow the conversation in that pr up to around May 2 for relevant comment
> rework Config ctors v2

- src/Confluent.Kafka/ConsumeResult.cs
- src/Confluent.Kafka/Exceptions/MessageNullException.cs
resolves #919 by throwing a more verbose exception when accessing the
convenience properties in ConsumeResult.
> prevent NullReferenceExceptions on ConsumeResult

- CHANGELOG.md
- examples/AvroBlogExamples/Program.cs
- examples/AvroGeneric/Program.cs
- examples/AvroSpecific/Program.cs
- src/Confluent.SchemaRegistry/SchemaRegistryConfig.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Consumer_AutoCommit.cs
- test/Confluent.SchemaRegistry.IntegrationTests/Tests/BasicAuth.cs
- test/Confluent.SchemaRegistry.IntegrationTests/Tests/Failover.cs
- test/Confluent.SchemaRegistry.IntegrationTests/Tests/FillTheCache.cs
- test/Confluent.SchemaRegistry.IntegrationTests/Tests/GetAllSubjects.cs
- test/Confluent.SchemaRegistry.IntegrationTests/Tests/GetId.cs
- test/Confluent.SchemaRegistry.IntegrationTests/Tests/GetLatestSchema.cs
- test/Confluent.SchemaRegistry.IntegrationTests/Tests/GetSchemaById.cs
- test/Confluent.SchemaRegistry.IntegrationTests/Tests/GetSchemaBySubjectAndVersion.cs
- test/Confluent.SchemaRegistry.IntegrationTests/Tests/GetSubjectVersions.cs
- test/Confluent.SchemaRegistry.IntegrationTests/Tests/IsCompatible.cs
- test/Confluent.SchemaRegistry.IntegrationTests/Tests/RegisterIncompatibleSchema.cs
- test/Confluent.SchemaRegistry.IntegrationTests/Tests/RegisterSameSchemaTwice.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests/AutoRegisterSchemaDisabled.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests/AvroAndRegular.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests/ConsumeIncompatibleTypes.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests/ConsumePartitionEOF.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests/PrimitiveTypes.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests/ProduceConsume.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests/ProduceConsumeGeneric.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests/ProduceGenericMultipleTopics.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests/ProduceIncompatibleTypes.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests/ProduceInvalid.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests/SyncOverAsync.cs
- test/Confluent.SchemaRegistry.UnitTests/CachedSchemaRegistryClient.cs
as noted in #1070, the `SchemaRegistry` prefixes on the config property names are redundant / pointless. Retaining them in the underlying property name strings (and their corresponding constants) though.
> Depreciate SchemaRegistry property name prefix

- src/ConfigGen/Program.cs
- src/Confluent.Kafka/Config.cs
- src/Confluent.Kafka/Config_gen.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Producer_Produce.cs
Added a  new GetDouble function and replaced GetEnum on LingerMs getter.
GetEnum throws an exception of ArgumentException when it tries System.Enum.Parse(typeof(double), "3.5", ignoreCase: true); ("3.5" is just used as an example).
> Add a new config GetDouble function. Fix LingerMs

- src/Confluent.Kafka/Impl/SafeKafkaHandle.cs
- test/Confluent.Kafka.IntegrationTests/Tests/AdminClient_NullReferenceChecks.cs
Partially addresses #864.
I've audited the AdminClient and ProducerClient for segfaults and replaced them with null reference exceptions. I placed the unit tests in their own test-class for null reference checks.
> #864: Added Null Reference Checks to SafeKafkaHandle

- test/Confluent.SchemaRegistry.IntegrationTests/README.md
- test/Confluent.SchemaRegistry.IntegrationTests/docker-compose.yaml
afaik it's not necessary to have separate zookeeper/kafka instances to drive two schema registry instances, but I failed to get it working, don't want to dwell on it, and doing it this way is not a big deal so please lgtm thks.
> add noauth SR instance to docker-compose file

- src/Confluent.Kafka/Consumer.cs
- src/Confluent.Kafka/IConsumer.cs
related to #1160
This version just exposes the `Consume(int)` method.
Unfortunately moving the CancellationToken overload to an extension method does not work as it needs access to `cancellationDelayMaxMs` which is pulled from config in the `Consumer` impl. So not available to the extension in a "nice" way.
I did a search in github for  "dotnet.cancellation.delay.max.ms". Only a single hit outside Confluent.Kafka. I haven't seen anyone in "Corp world" use it either. 100ms seems like a reasonable value. We could just expose it as a default param on the method? And remove the config option, leave it up to the dev?
Also the `Consume(TimeStamp)` overload is referred to all over the place in xmldoc. Mostly codegen so probably not that big of a deal.
I do like extensions for this kind of thing. …
> expose `Consume(int)`

- src/Confluent.Kafka/Impl/SafeKafkaHandle.cs
`ListGroups(TimeSpan)` always fails due to passing group=`null`. Which then trips the null check.
This PR just moves the null check to `ListGroups(group, TimeSpan)`.
Failure and fix proved by running the example AdminClient with something like:
`dotnet .\AdminClient.dll localhost:29092 list-groups`
> ListGroups [BUG]

- src/Confluent.Kafka/Consumer.cs
- src/Confluent.Kafka/Library.cs
- src/Confluent.Kafka/Producer.cs
- test/Confluent.Kafka.IntegrationTests/Tests/ClientNameVersion.cs
note: `AdminClient` utilizes a producer instance under the covers and doesn't need to be explicitly updated.
> Expose client name and version to brokers

- examples/AdminClient/Program.cs
- examples/AvroBlogExamples/Program.cs
- examples/AvroGeneric/Program.cs
- examples/AvroSpecific/Program.cs
- examples/ConfluentCloud/Program.cs
- examples/Consumer/Program.cs
- examples/Protobuf/Program.cs
- examples/Transactions/Program.cs
- src/Confluent.Kafka/ConsumeResult.cs
- test/Confluent.Kafka.IntegrationTests/Tests/AssignOverloads.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Builder_CustomDefaults.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Consumer_DisableHeaders.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Consumer_DisableTimestamps.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Headers.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Ignore.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Producer_Handles.cs
- test/Confluent.Kafka.Transactions/TestConsumer.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests_Avro/AvroAndRegular.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests_Avro/PrimitiveTypes.cs
- test/Confluent.SchemaRegistry.Serdes.UnitTests/Configuration.cs
The message convenience properties on `ConsumeResult` were added at a time when it was never the case that `ConsumeResult.Message` could be `null`. Soon after, this became possible but the properties were never removed. They're a recurring source of confusion, so i'm marking them as obsolete.
@edenhill
> Made message convenience properties on ConsumeResult obsolete

- src/Confluent.SchemaRegistry.Serdes.Json/JsonDeserializer.cs
- src/Confluent.SchemaRegistry.Serdes.Json/JsonSerializer.cs
- test/Confluent.SchemaRegistry.Serdes.UnitTests/JsonSerializeDeserialize.cs
I've encountered issues validating schemas for contracts that rely for example on a JSON converter, or when it is necessary to use a different contract resolver. I dislike having to use `JsonConvert.DefaultSettings` for this as this can easily be changed mistakenly for other use cases, and thus breaking schema validation.
This PR makes it possible to pass `JsonSchemaGeneratorSettings` to the JSON (de)serializer.
> Adds (optional) JsonSchemaGeneratorSettings to JsonSerializer and JsonDeserializer for custom control over JSON schema generation.

- src/Confluent.SchemaRegistry.Serdes.Json/JsonDeserializer.cs
- src/Confluent.SchemaRegistry.Serdes.Json/JsonSerializer.cs
Parameterless constructor restriction removed. No need to restrict/forced to create contracts with a parameterless constructor. Since Newtonsoft Json is used, the library is perfectly capable of (de)serializing contracts with private setters and constructor parameters following a naming convention, parameter names names correspond to prop names.
This change will allow serialization of contracts with private setters (immutable) and parameterized constructors.
> Json serialization

- src/Confluent.Kafka/Producer.cs
In `Producer.ProduceAsync` method inner exception is included when creating `ProduceException` exception
```csharp
catch (Exception ex)
{
throw new ProduceException<TKey, TValue>(
new Error(ErrorCode.Local_KeySerialization),
new DeliveryResult<TKey, TValue>
{
Message = message,
TopicPartitionOffset = new TopicPartitionOffset(topicPartition, Offset.Unset)
},
ex); // <-- inner exception is included
}
```
But in synchronous version `Producer.Produce` it is not.
This change makes both methods to handle exception in same way.
> Producer.Produce improve error handling

- examples/Web/KafkaClientHandle.cs
I wrote the `Dispose` method, but forgot to mark the class as `IDisposable`, which means the framework won't pick up the class as being disposable and won't call the `Dispose` method.
This arguably highlights a flaw (some would say tradeoff) in the framework design imo. The type system should pick up on things like this.
> Added IDisposable to Web example KafkaClientHandle

- src/Confluent.Kafka/Handle.cs
Reason for change:
The ConsumerBuilder starts logging messages to LogHandler from within Build method with partially constructed IConsumer object (Kafka library handle is null). There is no way to determine whether the IConsumer properties can be accessed without triggering an exception.
This property will allow to check whether Handle property in IConsumer interface is valid and therefore other properties and methods could be called.
> add IsInvalid property to Handle class

- examples/Web/appsettings.json
Updated SecurityProtocol to use C#-specific 'SaslSsl' value instead of librdkafka-specific 'sasl_ssl' value, as the example results in 'System.FormatException: sasl_ssl is not a valid value for SecurityProtocol.' when using the librdkafka value. Additionally, changed SaslMechanism from plain to Plain to align with enum value
> Web Example Authentication Updates

- CHANGELOG.md
- README.md
- examples/AdminClient/AdminClient.csproj
- examples/AvroBlogExamples/AvroBlogExamples.csproj
- examples/AvroGeneric/AvroGeneric.csproj
- examples/AvroSpecific/AvroSpecific.csproj
- examples/ConfluentCloud/ConfluentCloud.csproj
- examples/Consumer/Consumer.csproj
- examples/Consumer/Program.cs
- examples/ExactlyOnce/ExactlyOnce.csproj
- examples/ExactlyOnceOldBroker/ExactlyOnceOldBroker.csproj
- examples/JsonSerialization/JsonSerialization.csproj
- examples/MultiProducer/MultiProducer.csproj
- examples/Producer/Producer.csproj
- examples/Protobuf/Protobuf.csproj
- examples/Web/Web.csproj
- src/ConfigGen/ConfigGen.csproj
- src/Confluent.Kafka/Confluent.Kafka.csproj
- src/Confluent.SchemaRegistry.Serdes.Avro/Confluent.SchemaRegistry.Serdes.Avro.csproj
- src/Confluent.SchemaRegistry.Serdes.Json/Confluent.SchemaRegistry.Serdes.Json.csproj
- src/Confluent.SchemaRegistry.Serdes.Protobuf/Confluent.SchemaRegistry.Serdes.Protobuf.csproj
- src/Confluent.SchemaRegistry/Confluent.SchemaRegistry.csproj
-> 1.7.0-RC4. Also updated `System.Net.Http to v4.3.4 (CVE-2018-8292). Also improved rebalance console output in the consumer example, which I have been using to observe partition shuffling.
> -> v1.7.0-RC4

- src/Confluent.Kafka/AdminClient.cs
- src/Confluent.Kafka/AdminClientBuilder.cs
We realised that we could not use the AdminClient in an authenticated fashion.
This PR should address that.
> [AdminClient] Allow AdminClient to be authenticated

- src/Confluent.SchemaRegistry.Serdes.Avro/Confluent.SchemaRegistry.Serdes.Avro.csproj
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Confluent.SchemaRegistry.Serdes.IntegrationTests.csproj
- test/Confluent.SchemaRegistry.Serdes.UnitTests/Confluent.SchemaRegistry.Serdes.UnitTests.csproj
Confluent.SchemaRegistry.Serdes.Avro references Apache.Avro 1.10.2. This PR changes reference to 1.11.0 in order to benefit from bugfixes.
> Using Apache.Avro 1.11.0

- README.md
If users aren't signed up then the existing URL just takes them to a login page with no indication of how to sign up.
> Change Slack URL

- examples/AdminClient/AdminClient.csproj
- examples/AvroBlogExamples/AvroBlogExamples.csproj
- examples/AvroGeneric/AvroGeneric.csproj
- examples/AvroSpecific/AvroSpecific.csproj
- examples/ConfluentCloud/ConfluentCloud.csproj
- examples/Consumer/Consumer.csproj
- examples/ExactlyOnce/ExactlyOnce.csproj
- examples/ExactlyOnceOldBroker/ExactlyOnceOldBroker.csproj
- examples/JsonSerialization/JsonSerialization.csproj
- examples/MultiProducer/MultiProducer.csproj
- examples/Producer/Producer.csproj
- examples/Protobuf/Protobuf.csproj
- src/ConfigGen/ConfigGen.csproj
- src/Confluent.Kafka/Confluent.Kafka.csproj
- src/Confluent.Kafka/Internal/Extensions/String.cs
- src/Confluent.Kafka/Producer.cs
- test/Confluent.Kafka.Benchmark/Confluent.Kafka.Benchmark.csproj
- test/Confluent.Kafka.IntegrationTests/Confluent.Kafka.IntegrationTests.csproj
- test/Confluent.Kafka.SyncOverAsync/Confluent.Kafka.SyncOverAsync.csproj
- test/Confluent.Kafka.Transactions/Confluent.Kafka.Transactions.csproj
- test/Confluent.Kafka.UnitTests/Confluent.Kafka.UnitTests.csproj
- test/Confluent.Kafka.VerifiableClient/Confluent.Kafka.VerifiableClient.csproj
- test/Confluent.SchemaRegistry.IntegrationTests/Confluent.SchemaRegistry.IntegrationTests.csproj
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Confluent.SchemaRegistry.Serdes.IntegrationTests.csproj
- test/Confluent.SchemaRegistry.Serdes.UnitTests/Confluent.SchemaRegistry.Serdes.UnitTests.csproj
- test/Confluent.SchemaRegistry.UnitTests/Confluent.SchemaRegistry.UnitTests.csproj
netcoreapp2.1 is now out of long term support.
Moving to net5.0 not net6.0 as one of the test projects hangs on net6.0. This seems to be a problem with the test framework not the tests according to some quick research. Couldn't quickly figure out how to fix it.
Note: This PR does not affect framework compatibility of any of the libraries.
CancellationTokenRegistration and CancellationToken are structs, so the newer compiler warns me, so can't be null.
> netcoreapp2.1 -> net5.0

- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests_Avro/ConsumePartitionEOF.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests_Protobuf/ProduceConsumeNested.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests_Protobuf/ProduceConsumeSchemaManyMessages.cs
- not blocking on the ProduceAsync call is a heisenbug. it only started mattering after I upgraded to .net 5.0
- the other two tests have been broken for a long time and the break is due to the change in protobuf serialization format (now resolved). the code i've removed in this PR is redundant - it's more there for informational purposes. it checks the serialization format byte by byte in the test. the important thing to test (which is done immediately above this) is that the deserialization actually works. That implies the data is serialized correctly.
> Fix broken Schema Registry serde integration tests

- src/Confluent.Kafka/Producer.cs
- **EnableDeliveryReports** is set to `false` in producer configuration
- no delivery handler callback is specified during the call to `producer.Produce(...)` method (aka the delivery handler is `null`)
- during the call to **produce1**
_pass the delivery handler as is to **produce2**_
- during the call to **produce2**
_**ProduceImpl** is being called with a newly created instance of `TypedDeliveryHandlerShim_Action`_
- during the call to **ProduceImpl**
_after the check `if (this.enableDeliveryReports && deliveryHandler != null)` the control flow follows the **else** branch of the **if** statement and calls `KafkaHandle.Produce` method with an `IntPtr.Zero` value for delivery handler thus effectively discarding the passed value for delivery handler => **we have made the unnecessary …
> Reduce the number of creation times of TypedDeliveryHandlerShim_Action

- src/Confluent.Kafka/Confluent.Kafka.csproj
- src/Confluent.SchemaRegistry/Confluent.SchemaRegistry.csproj
- test/Confluent.Kafka.UnitTests/Confluent.Kafka.UnitTests.csproj
It seems like omnisharp (IDE intellisense helper) uses the first listed framework in TargetFrameworks. It makes life better therefore to specify a maximally compatible framework first. This change works around issues i'm having with vscode on osx.
> Change framework order to avoid omnisharp issues

- src/Confluent.SchemaRegistry/CachedSchemaRegistryClient.cs
Fixes #1767 (CachedSchemaRegistryClient.cs does not support passwords that include ':' character)
> Limit splitting auth info to a max of 2 parts

- examples/Consumer/Program.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests_Avro/AutoRegisterSchemaDisabled.cs
new Guid() gives `00000000-0000-0000-0000-000000000000`, `Guid.NewGuid()` gives a new unique guid, which is the intent.
> Fix inadvertent and misleading use of new Guid()

- examples/Consumer/Program.cs
For #1747.
Changes done:
1. For `Run_Consume` updated to use `StoreOffset` instead of `Commit`.
2. For `Run_ManualAssign` updated `GroupId` to a static id so that a new group isn't created on every restart.
> Fix consumer example

- CHANGELOG.md
- src/Confluent.Kafka/Consumer.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Consumer_Drain.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Consumer_StoreOffset_ErrState.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Consumer_Subscription_DisjointTopics.cs
- test/Confluent.Kafka.IntegrationTests/Tests/Consumer_Subscription_Regex.cs
Added default rebalance callback handler to prevent consumers not having partition revoked handlers from entering into the erroneous state.
Consumers might enter into erroneous state as they might have lost the partitions during rebalance but still they are committing the offsets for them as they aren't aware of the changes.
Some changes were needed to the tests to make sure the rebalance is running properly.
Verified all the integration tests are working.
> Add default rebalance callback

- service.yml
Taken reference from internal wikis and existing binding files
* https://github.com/confluentinc/confluent-kafka-go/blob/master/service.yml
* https://github.com/confluentinc/confluent-kafka-python/blob/master/service.yml
Will create the semaphore project once this is merged and test the CI from there.
> Add service.yml for adding project to the semaphore CI

- .semaphore/semaphore.yml
Add semaphore config having jobs:
1. Linux x64 build and test
2. OSX x64 build and test
3. Windows x64 build and test
4. Artifacts from windows build.
Have commented integration tests for now as they are flaky.
1. Integration tests on Linux
2. Schema registry and serdes integration tests on Linux
> Add semaphore config

- test/Confluent.Kafka.IntegrationTests/Tests/Producer_CustomPartitioner.cs
From #1955. 
Updated test for null key producer so that assertions inside the partitioner are actually called.
Verified through logs that the partitioner is getting called.
> Disable sticky partitioning for null key producer in CustomPartitionerTest

- CHANGELOG.md
- src/Confluent.Kafka/AdminClient.cs
- src/Confluent.Kafka/Consumer.cs
- src/Confluent.Kafka/IClient.cs
- src/Confluent.Kafka/Impl/LibRdKafka.cs
- src/Confluent.Kafka/Impl/NativeMethods/NativeMethods.cs
- src/Confluent.Kafka/Impl/NativeMethods/NativeMethods_Alpine.cs
- src/Confluent.Kafka/Impl/NativeMethods/NativeMethods_Centos6.cs
- src/Confluent.Kafka/Impl/NativeMethods/NativeMethods_Centos7.cs
- src/Confluent.Kafka/Impl/SafeKafkaHandle.cs
- src/Confluent.Kafka/Producer.cs
- test/Confluent.Kafka.IntegrationTests/Tests/SetSaslCredentials.cs
The dotnet binding for rd_kafka_sasl_set_credentials.
This binding is present in the go client only at the moment.
Ref: https://github.com/confluentinc/librdkafka/pull/4033
> Add SetSaslCredentials binding

- CHANGELOG.md
- src/Confluent.Kafka/Impl/Metadata.cs
- test/Confluent.Kafka.IntegrationTests/Tests/AdminClient_ListGroups.cs
Fixes #1995.
There was an extra field in `rd_kafka_group_member_info` which wasn't matching with the librdkafka struct and was causing mismatch in the .NET binding leading to the `overflow` exception.
Also added a new integration test. The AdminClient_ListGroups test verifies that the ListGroups API returns the expected group information. This test ensures that the bug has been fixed.
> Add AdminClient_ListGroups test and remove unused field in Metadata struct

- CHANGELOG.md
- src/Confluent.SchemaRegistry.Serdes.Avro/SpecificDeserializerImpl.cs
- src/Confluent.SchemaRegistry.Serdes.Avro/SpecificSerializerImpl.cs
Use `ISpecificRecord` interface to get the schema instead of reflecting the static `_SCHEMA` field which is not a part of an interface. 
Address #1958.
> Use schema from ISpecificRecord instead of reflecting a field

- CHANGELOG.md
- src/Confluent.Kafka/TopicPartitionOffset.cs
Fix a backward compatibility issue in the TopicPartitionOffset constructor by reintroducing the original constructor and overloading it to separately accommodate the optional parameters.
* Reintroduces the original constructor.
* Adds an overloaded constructor for additional parameters.
Referring - https://github.com/confluentinc/confluent-kafka-dotnet/pull/2061 and fixes #2060
___
Integration tests
> Fix Backward Compatibility Issue in TopicPartitionOffset Constructor

- README.md
Adding a link to the Apache Kafka for .NET training course on developer.confluent.io.
> Add a link to the Confluent Apache Kafka for .NET Developers training course.

- test/Confluent.Kafka.IntegrationTests/Tests/AdminClient_AlterConfigs.cs
- test/Confluent.Kafka.IntegrationTests/Tests/AdminClient_IncrementalAlterConfigs.cs
in integration test to avoid disconnections from broker 0.
It seems the broker is disconnecting when available threads are exhausted, this problem is more evident when number of broker thread was reduced to 2 instead of the default of 3.
> Increase number of network threads

- CHANGELOG.md
- src/Confluent.Kafka/Consumer.cs
- src/Confluent.Kafka/IConsumer.cs
- src/Confluent.Kafka/IConsumerExtensions.cs
Fixes a breaking change in the IConsumer interface introduced by #2027 by replacing the interface method and the implementation on Consumer with an extension method on IConsumer. This ensures that existing implementations of IConsumer remain unbroken and have the same functionality as the default Consumer implementation.
Referenced from #2067.
Integration tests
> Fix IConsumer breaking change

- examples/AdminClient/Program.cs
- src/Confluent.Kafka/Admin/ListOffsetsReport.cs
- src/Confluent.Kafka/Admin/ListOffsetsResult.cs
- src/Confluent.Kafka/Admin/OffsetSpec.cs
- src/Confluent.Kafka/AdminClient.cs
- src/Confluent.Kafka/Impl/SafeKafkaHandle.cs
- test/Confluent.Kafka.IntegrationTests/Tests/AdminClient_ListOffsets.cs
- test/Confluent.Kafka.UnitTests/Admin/DescribeTopicsError.cs
- test/Confluent.Kafka.UnitTests/Admin/ListOffsetsError.cs
DescribeTopics and ListOffsets should return an empty output if and empty input is passed as parameter.
Consistent with Java and user friendly for users using filter and map.
> Fix calls with empty lists

- .semaphore/semaphore.yml
- Update mac agent to 13.5 which is close to developer's local versions.
- new mac agent syntax is same as ubuntu agents
> ci: Update mac build agents versions

- CHANGELOG.md
- src/Confluent.Kafka/Confluent.Kafka.csproj
- src/Confluent.SchemaRegistry.Serdes.Avro/Confluent.SchemaRegistry.Serdes.Avro.csproj
- src/Confluent.SchemaRegistry.Serdes.Json/Confluent.SchemaRegistry.Serdes.Json.csproj
- src/Confluent.SchemaRegistry.Serdes.Protobuf/Confluent.SchemaRegistry.Serdes.Protobuf.csproj
- src/Confluent.SchemaRegistry/Confluent.SchemaRegistry.csproj
This sets additional package info and switch to licence expression rather than url. Also lint csproj to be consistantly tabbed.
closes #2183
> #2183 switch to licence expression + repo info

- src/Confluent.SchemaRegistry.Encryption.Azure/AzureKmsClient.cs
- src/Confluent.SchemaRegistry.Encryption.Azure/Confluent.SchemaRegistry.Encryption.Azure.csproj
Fix algorithm used by Azure Key Vault to be RsaOaep256, to be consistent with the Java and golang clients, so that the dotnet client can interoperate with them.
> Fix Azure algorithm to RsaOaep256

- src/Confluent.Kafka/Confluent.Kafka.csproj
Remove System.Memory as a dependency for dotnet 6 TFM
closes #2181
> #2181 Remove System.Memory from Dotnet 6

- examples/JsonWithReferences/JsonWithReferences.csproj
- examples/JsonWithReferences/Program.cs
- src/Confluent.SchemaRegistry.Serdes.Json/Confluent.SchemaRegistry.Serdes.Json.csproj
- src/Confluent.SchemaRegistry.Serdes.Json/JsonDeserializer.cs
- src/Confluent.SchemaRegistry.Serdes.Json/JsonSchemaResolver.cs
- src/Confluent.SchemaRegistry.Serdes.Json/JsonSerializer.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Confluent.SchemaRegistry.Serdes.IntegrationTests.csproj
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests_Json/UseReferences.cs
- test/Confluent.SchemaRegistry.Serdes.UnitTests/Confluent.SchemaRegistry.Serdes.UnitTests.csproj
- test/Confluent.SchemaRegistry.Serdes.UnitTests/JsonSerializeDeserialize.cs
(Original PR: https://github.com/confluentinc/confluent-kafka-dotnet/pull/2185)
Fixes https://github.com/confluentinc/confluent-kafka-dotnet/issues/2169
A few notes:
- This is a breaking change, and should be included in a major version release only, as we're dropping support for NJsonSchema v10. This change **will** impact users that manage their own references to NJsonSchema v10.
- Newtonsoft.Json-based generators have been moved to a separate NuGet package, so the reference to NJsonSchema has been replaced with a reference to NJsonSchema.NewtonsoftJson. See [NSwag 14 announcement](https://github.com/RicoSuter/NSwag/issues/4524) and [NJsonSchema v11 release notes](https://github.com/RicoSuter/NJsonSchema/releases/tag/v11.0.0).
- `EnumHandling` no longer exists, so the …
> Update NJsonSchema to v11

- src/Confluent.SchemaRegistry.Serdes.Protobuf/AssemblyInfo.cs
- src/Confluent.SchemaRegistry.Serdes.Protobuf/ProtobufUtils.cs
- test/Confluent.SchemaRegistry.Serdes.UnitTests/Confluent.SchemaRegistry.Serdes.UnitTests.csproj
- test/Confluent.SchemaRegistry.Serdes.UnitTests/ProtoSerializeDeserialize.cs
This PR fixes issues in the ProtobufUtils Parse function that prevented the ProtobufSerializer from serializing any message that contained well known types. This is a show stopper defect for all versions past 2.4.0 and should be prioritized
> Fix ProtobufUtils Parse function (Showstopper defect) (#2297)

- examples/JsonWithReferences/JsonWithReferences.csproj
- examples/JsonWithReferences/Program.cs
- src/Confluent.SchemaRegistry.Serdes.Json/Confluent.SchemaRegistry.Serdes.Json.csproj
- src/Confluent.SchemaRegistry.Serdes.Json/JsonDeserializer.cs
- src/Confluent.SchemaRegistry.Serdes.Json/JsonSchemaResolver.cs
- src/Confluent.SchemaRegistry.Serdes.Json/JsonSerializer.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Confluent.SchemaRegistry.Serdes.IntegrationTests.csproj
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests_Json/UseReferences.cs
- test/Confluent.SchemaRegistry.Serdes.UnitTests/Confluent.SchemaRegistry.Serdes.UnitTests.csproj
- test/Confluent.SchemaRegistry.Serdes.UnitTests/JsonSerializeDeserialize.cs
We'll add these back once we get our build system Semaphore working with dotnet 8.0
> Temporarily revert NJsonSchema v11 changes

- src/Confluent.SchemaRegistry.Serdes.Avro/GenericDeserializerImpl.cs
- src/Confluent.SchemaRegistry.Serdes.Avro/GenericSerializerImpl.cs
- src/Confluent.SchemaRegistry.Serdes.Avro/SpecificDeserializerImpl.cs
- src/Confluent.SchemaRegistry.Serdes.Avro/SpecificSerializerImpl.cs
- src/Confluent.SchemaRegistry.Serdes.Json/JsonDeserializer.cs
- src/Confluent.SchemaRegistry.Serdes.Json/JsonSerializer.cs
- src/Confluent.SchemaRegistry.Serdes.Protobuf/ProtobufDeserializer.cs
- src/Confluent.SchemaRegistry.Serdes.Protobuf/ProtobufSerializer.cs
- src/Confluent.SchemaRegistry/AsyncSerde.cs
- src/Confluent.SchemaRegistry/Rest/RestService.cs
- test/Confluent.SchemaRegistry.Serdes.UnitTests/BaseSerializeDeserialize.cs
- test/Confluent.SchemaRegistry.Serdes.UnitTests/SerializeDeserialize.cs
Fixes https://github.com/confluentinc/confluent-kafka-dotnet/issues/2265
> Fix use of RecordNameStrategy (#40)

- src/Confluent.SchemaRegistry.Serdes.Json/JsonSchemaResolver.cs
- test/Confluent.SchemaRegistry.Serdes.UnitTests/JsonSerializeDeserialize.cs
Fix JSON Schema ref handling.  Before the code relied on the reference name also being the `$id` for the referenced schema.
> DGS-18985 Fix JSON Schema ref handling

- src/Confluent.SchemaRegistry.Serdes.Protobuf/ProtobufSerializer.cs
- src/Confluent.SchemaRegistry.Serdes.Protobuf/ProtobufSerializerConfig.cs
- src/Confluent.SchemaRegistry/ReferenceSubjectNameStrategy.cs
This feature allows producers to specify configuration for ReferenceSubjectNameStrategy the following enumeration values:
- `ReferenceName` -> (default): Use the reference name as the subject name.
- `Qualified` -> Given a reference name, replace slashes with dots, and remove the .proto suffix to obtain the subject name. For example, mypackage/myfile.proto becomes mypackage.myfile. (This provides feature parity with java client)
- `Custom` -> Use a custom reference subject name strategy resolver to determine the subject name. This is done by implementing ICustomReferenceSubjectNameStrategy and assigning instance to ProtobufSerializerConfig property CustomReferenceSubjectNameStrategy
An internal team is using java has implemented their Schema Registry with …
> Feature: Added Qualified and Custom reference name strategy approaches for protobuf references (Schema Registry)

- src/Confluent.SchemaRegistry.Encryption/CachedDekRegistryClient.cs
- src/Confluent.SchemaRegistry.Encryption/FieldEncryptionExecutor.cs
- src/Confluent.SchemaRegistry.Encryption/Rest/DekRestService.cs
- src/Confluent.SchemaRegistry.Rules/CelExecutor.cs
- src/Confluent.SchemaRegistry.Rules/CelFieldExecutor.cs
- src/Confluent.SchemaRegistry.Rules/JsonataExecutor.cs
- src/Confluent.SchemaRegistry/AsyncSerde.cs
- src/Confluent.SchemaRegistry/CachedSchemaRegistryClient.cs
- src/Confluent.SchemaRegistry/ErrorAction.cs
- src/Confluent.SchemaRegistry/FieldRuleExecutor.cs
- src/Confluent.SchemaRegistry/IRuleBase.cs
- src/Confluent.SchemaRegistry/ISchemaRegistryClient.cs
- src/Confluent.SchemaRegistry/NoneAction.cs
- src/Confluent.SchemaRegistry/Rest/RestService.cs
This applies the fixes https://github.com/confluentinc/confluent-kafka-dotnet/pull/2346 and https://github.com/confluentinc/confluent-kafka-dotnet/pull/2128 to the DEK Registry client
> Fix SSL CA cert validation and proxy for DEK Registry client

- src/Confluent.SchemaRegistry.Encryption/CachedDekRegistryClient.cs
- src/Confluent.SchemaRegistry.Encryption/Rest/DekRestService.cs
- src/Confluent.SchemaRegistry/CachedSchemaRegistryClient.cs
- src/Confluent.SchemaRegistry/Rest/RestService.cs
- src/Confluent.SchemaRegistry/SchemaRegistryConfig.cs
Add retry logic to RestService. We implement exponential backoff with full jitter per https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/
> Add retry logic to RestService

- src/Confluent.SchemaRegistry/Rest/DataContracts/RegisteredSchema.cs
- src/Confluent.SchemaRegistry/Rest/DataContracts/Schema.cs
These properties will be removed in a future major release. These were actually marked as obsolete in the past, but were temporarily removed.  This just re-adds the obsolete annotations.
> Mark some deprecated properties as obsolete in Schema

- src/Confluent.SchemaRegistry.Encryption.HcVault/HcVaultKmsClient.cs
- src/Confluent.SchemaRegistry.Encryption.HcVault/HcVaultKmsDriver.cs
- src/Confluent.SchemaRegistry.Encryption/LocalKmsClient.cs
- src/Confluent.SchemaRegistry.Encryption/LocalKmsDriver.cs
For consistency, move the env var lookup from the client to the driver.
> MINOR refactor env var lookup for consistency with other repos

- 3RD_PARTY.md
This PR introduces the Kafka Core library to the list of third-party libraries.
Kafka Core empowers developers to effortlessly build robust .NET applications on top of Confluent Kafka, focusing on simplicity, maintainability, and extensibility. With intuitive abstractions and builders, it introduces powerful features that enhance functionality and extend the official library's capabilities.
> Add Kafka Core to Third-Party Libraries

- src/Confluent.SchemaRegistry/AsyncSerde.cs
- src/Confluent.SchemaRegistry/CachedSchemaRegistryClient.cs
This PR addresses a significant performance issue observed when enabling the schema registry for consumers using the Protobuf deserializer. The consumption time for 600k messages shows a drastic difference:
- **With Schema Registry:**  
Elapsed time: `00:00:33.7949289`
- **Without Schema Registry:**  
Elapsed time: `00:00:07.8086635`
The root cause was identified as the usage of `SemaphoreSlim` locks with a regular `.NET Dictionary` on the consumer's hot path. This PR optimizes the implementation to mitigate this bottleneck, aligning the performance closer to Java's implementation, which does not suffer from this issue.
> Improve lock utilization on the consumer hot path

- src/Confluent.SchemaRegistry/CachedSchemaRegistryClient.cs
- src/Confluent.SchemaRegistry/Utils.cs
This PR improves the performance of the Base64 encoding check, which is performed for every message processed by the consumer. This change complements the work done in #2370.
Below are the results of benchmarking the new implementation (Base64.IsValid) against the existing Convert.FromBase64String approach:
```
| Method           | Mean          | Error        | StdDev       |
|----------------- |--------------:|-------------:|-------------:|
| IsBase64         |      24.52 ns |     0.074 ns |     0.066 ns |
| FromBase64String | 138,883.49 ns | 2,535.710 ns | 2,247.841 ns |
```
The code used to produce the benchmark results::
```csharp
class Program
{
static void Main(string[] args)
{
BenchmarkRunner.Run<IsBase64StringBenchmark>();
}
}
public class IsBase64StringBenchmark
{
private …
```
> Improve perf of base64 encoding check on a consumer hot path

- src/Confluent.SchemaRegistry.Serdes.Json/JsonDeserializer.cs
This branch was missed when adding the validate config in https://github.com/confluentinc/confluent-kafka-dotnet/pull/2350
> Add missing validate check

- src/Confluent.SchemaRegistry.Serdes.Protobuf/ProtobufSerializer.cs
- src/Confluent.SchemaRegistry.Serdes.Protobuf/ProtobufSerializerConfig.cs
- src/Confluent.SchemaRegistry/AsyncSerde.cs
- test/Confluent.SchemaRegistry.Serdes.IntegrationTests/Tests_Protobuf/ProduceConsumeGoogleRef.cs
What
----
By default, skip known types when registering a Protobuf schema.  This is because these known types are builtin and not used when resolving a Protobuf schema.  The default is changed to match the default behavior of the other clients.
Checklist
- Default of skipKnownTypes is changed to true to match other clients.
- Existing tests provide sufficient coverage
References
----------
JIRA: 
Test & Review
------------
> Set skipKnownTypes default to be consistent with other clients

- src/Confluent.SchemaRegistry.Serdes.Avro/GenericSerializerImpl.cs
- src/Confluent.SchemaRegistry.Serdes.Avro/SpecificSerializerImpl.cs
- test/Confluent.SchemaRegistry.Serdes.UnitTests/BaseSerializeDeserialize.cs
- test/Confluent.SchemaRegistry.Serdes.UnitTests/SerializeDeserialize.cs
What
----
Ensure Avro serde caches per subject.  Previously caching of schema IDs for primitive types did not account for the subject.
Checklist
- No
- Yes
References
----------
JIRA: 
Test & Review
------------
> DGS-19409 Ensure Avro serde caches per subject

- src/Confluent.SchemaRegistry.Serdes.Json/JsonDeserializer.cs
- src/Confluent.SchemaRegistry.Serdes.Json/JsonSerializer.cs
- test/Confluent.SchemaRegistry.Serdes.UnitTests/JsonSerializeDeserialize.cs
What
----
Fix JSON Schema validation to use latest schema if needed.
Fixes https://github.com/confluentinc/confluent-kafka-dotnet/issues/2401
Checklist
References
----------
JIRA: 
Test & Review
------------
> DGS-19627 Fix JSON Schema validation to use latest schema if needed

- src/Confluent.SchemaRegistry.Serdes.Protobuf/ProtobufUtils.cs
- test/Confluent.SchemaRegistry.Serdes.UnitTests/Generated/Person.cs
- test/Confluent.SchemaRegistry.Serdes.UnitTests/ProtoSerializeDeserialize.cs
- test/Confluent.SchemaRegistry.Serdes.UnitTests/proto/Person.proto
What
----
Support Protobuf oneof fields in Data Contract rules.
The file Person.cs is generated and can be ignored.
Checklist
References
----------
JIRA: 
Test & Review
------------
> DGS-19711 Support Protobuf oneof fields in Data Contract rules

- src/Confluent.SchemaRegistry/CachedSchemaRegistryClient.cs
What
----
A recent [PR](https://github.com/confluentinc/confluent-kafka-dotnet/pull/2429) added a re-entrant lock attempt.  This PR reverts it.
Checklist
References
----------
JIRA: 
Test & Review
------------
> Revert re-entrant lock attempt during LookupSchemaAsync

- src/Confluent.SchemaRegistry/CachedSchemaRegistryClient.cs
What
----
This PR is a follow-up to https://github.com/confluentinc/confluent-kafka-dotnet/pull/2429.
It replaces the thread-unsafe Dictionary with its thread-safe variant, ConcurrentDictionary.
The main goal is to eliminate the need to acquire a lock for cache lookups, improving performance in concurrent scenarios.
Checklist
- No changes in public API
- Just a perf optimization, no functional changes.
@rayokota Could you please take a look?
> Use ConcurrentDictionary as default cache for Schema Registry client

- CHANGELOG.md
- src/Confluent.Kafka/Admin/ConfigSource.cs
- test/Confluent.Kafka.IntegrationTests/Tests/AdminClient_IncrementalAlterConfigs.cs
This PR intends to add support for Group Resource type for IncrementalAlterConfigs API as specified in KIP 848 and extended the DescribeConfigs support till API version 3.
Additional changed the integration test to check for Group Resource Type.
Librdkafka PR: https://github.com/confluentinc/librdkafka/pull/4939
I have tested it locally and it is working fine
dotnet test --filter "FullyQualifiedName=Confluent.Kafka.IntegrationTests.Tests.AdminClient_IncrementalAlterConfigs"
Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: < 1 ms - Confluent.Kafka.IntegrationTests.dll (net6.0)
Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: < 1 ms - Confluent.Kafka.IntegrationTests.dll (net8.0)
> KIP 848: Extend DescribeConfigs and IncrementalAlterConfigs to support GROUP Config

- src/Confluent.Kafka/SyncOverAsyncDeserializer.cs
- src/Confluent.Kafka/SyncOverAsyncSerializer.cs
What
----
This PR removes a redundant call to .ConfigureAwait(false) in a blocking context (.GetAwaiter().GetResult()), as it has no effect in such cases.
See Stephen Cleary’s [article](https://blog.stephencleary.com/2023/11/configureawait-in-net-8.html) on ConfigureAwait in .NET 8 for detailed explanation.
Checklist
* No
* Not required — behavior remains unchanged and is already covered.
@rayokota Could you please take a look?
> Remove redundant ConfigureAwait

- src/Confluent.SchemaRegistry.Serdes.Avro/GenericDeserializerImpl.cs
- src/Confluent.SchemaRegistry.Serdes.Avro/ReadOnlyMemoryStream.cs
- src/Confluent.SchemaRegistry.Serdes.Avro/SpecificDeserializerImpl.cs
What
----
This PR introduces a Stream adapter for ReadOnlyMemory<byte> to avoid copying payload during Avro deserialization. 
| Method      | Mean     | Error     | StdDev    | Gen0     | Gen1     | Gen2     | Allocated |
|------------ |---------:|----------:|----------:|---------:|---------:|---------:|----------:|
| Deserialize | 5.100 ms | 0.1014 ms | 0.2205 ms | 515.6250 | 515.6250 | 515.6250 |     40 MB |
| Method      | Mean     | Error     | StdDev    | Gen0     | Gen1     | Gen2     | Allocated |
|------------ |---------:|----------:|----------:|---------:|---------:|---------:|----------:|
| Deserialize | 3.614 ms | 0.0715 ms | 0.1614 ms | 632.8125 | 632.8125 | 632.8125 |  33.63 MB |
Checklist
* No
* Not required — behavior remains unchanged and is already …
> Avoid array copy on Avro deserialization

- src/Confluent.SchemaRegistry.Encryption/EncryptionExecutor.cs
- src/Confluent.SchemaRegistry.Encryption/KmsClientWrapper.cs
- test/Confluent.SchemaRegistry.Serdes.UnitTests/SerializeDeserialize.cs
What
----
Checklist
References
----------
JIRA: 
Test & Review
------------
> DGS-21595 Allow alternate KMS key IDs on a KEK 

- src/Confluent.SchemaRegistry.Encryption.HcVault/HcVaultKmsClient.cs
- src/Confluent.SchemaRegistry.Encryption.HcVault/HcVaultKmsDriver.cs
What
----
Add AppRole auth for HC Vault. Tested manually with local HC Vault instance with AppRole auth enabled.
Checklist
- [Y] Contains customer facing changes? Including API/behavior changes 
- [Y] Did you add sufficient unit test and/or integration test coverage for this PR?
- Covered by existing tests plus new manual testing.
References
----------
JIRA: 
Test & Review
------------
> DGS-22404 Add AppRole auth for HC Vault

- CHANGELOG.md
- examples/OAuthConsumer/Program.cs
- examples/OAuthOIDC/Program.cs
- examples/OAuthOIDCAzureIMDS/OAuthOIDCAzureIMDS.csproj
- examples/OAuthOIDCAzureIMDS/Program.cs
- examples/OAuthProducer/Program.cs
What
----
Checklist
References
----------
JIRA: 
Test & Review
------------
> OAuth Azure IMDS Kafka example
